### ISSUE TITLE
Exception while Shutting down service on dd-java-agent

### ISSUE THREAD

**Issue by cb-salaikumar** [DataDog/dd-trace-java#1145]
While shutting the service, we are facing the following exception.

Version : 0.39.0

Exception in thread "dd-trace-disruptor" java.lang.RuntimeException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@a45f265 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3a1fc733[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 179]
	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
	at com.lmax.disruptor.dsl.ExceptionHandlerWrapper.handleEventException(ExceptionHandlerWrapper.java:18)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:187)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@a45f265 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3a1fc733[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 179]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at datadog.trace.agent.common.writer.DDAgentWriter$TraceConsumer.reportTraces(DDAgentWriter.java:356)
	at datadog.trace.agent.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:322)
	at datadog.trace.agent.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:291)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)

**Comment by tylerbenson** [comment]
Thanks for the report.  I've submitted a PR that I think should resolve this issue: #1150.
