### ISSUE TITLE
NPE when using @Trace with the current master

### ISSUE THREAD

**Issue by olivier-andre** [DataDog/dd-trace-java#1205]
A simple hello world Java app throws an NPE (see below) when annotating a method with @Trace. Meanwhile, default automatic JVM metrics are sent just fine.
This happens with the current master sources.

It seems that the new serializer doesn't support the null span type used for custom spans.

[dd.trace 2020-02-07 11:33:24:997 +0100] [dd-trace-processor] DEBUG datadog.trace.agent.common.writer.ddagent.TraceProcessingDisruptor - Error while serializing trace
java.lang.NullPointerException
	at org.msgpack.core.MessagePacker.packString(MessagePacker.java:725)
	at datadog.trace.agent.common.serialization.MsgpackFormatWriter.writeString(MsgpackFormatWriter.java:35)
	at datadog.trace.agent.common.serialization.MsgpackFormatWriter.writeString(MsgpackFormatWriter.java:7)
	at datadog.trace.agent.common.serialization.FormatWriter.writeDDSpan(FormatWriter.java:95)
	at datadog.trace.agent.common.serialization.FormatWriter.writeTrace(FormatWriter.java:79)
	at datadog.trace.agent.common.writer.ddagent.DDAgentApi.serializeTrace(DDAgentApi.java:122)
	at datadog.trace.agent.common.writer.ddagent.TraceProcessingDisruptor$TraceSerializingHandler.onEvent(TraceProcessingDisruptor.java:72)
	at datadog.trace.agent.common.writer.ddagent.TraceProcessingDisruptor$TraceSerializingHandler.onEvent(TraceProcessingDisruptor.java:42)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tylerbenson** [comment]
@olivier-andre thanks for the report.  We'll make sure this is fixed before the next release.
