### ISSUE TITLE
Getting correlation IDs from logback-access with Tomcat 7

### ISSUE THREAD

**Issue by wuservices** [DataDog/dd-trace-java#1214]
I'm running Java 8 and Tomcat 7 with Spring MVC, Datadog Java agent version 0.42.0. I'm trying to get correlation IDs for APM to be logged with my **access** logs, but the trace and span IDs don't appear to be in context when the access logs are written.

I've followed the instructions for using [logback-access with Tomcat](http://logback.qos.ch/access.html#tomcat) and am also using Logstash to log JSON logs per the Datadog docs. To get Logback Access working to log each request / response from Tomcat, I've followed Logback's instructions for Tomcat to add the necessary classes and configuration to Tomcat's lib folder and I've added the following logback-access.xml to configure everything:
```xml
<configuration>
  <appender name="ACCESS_STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
      <providers>
        <timestamp/>
        <version/>
        <message/>
        <method/>
        <protocol/>
        <statusCode/>
        <requestedUrl/>
        <requestedUri/>
        <remoteHost/>
        <remoteUser/>
        <contentLength/>
        <elapsedTime/>
        <requestHeaders>
          <fieldName>request_headers</fieldName>
        </requestHeaders>
        <responseHeaders>
          <fieldName>response_headers</fieldName>
        </responseHeaders>
        <!-- Access logs don't support MDC, so we use our own provider: https://jira.qos.ch/browse/LOGBACK-1016 -->
        <provider class="com.example.logging.logback.DatadogTraceJsonProvider"/>
        <pattern>
          <pattern>{"source": "java", "sourcecategory": "access"}</pattern>
        </pattern>
      </providers>
    </encoder>
  </appender>
  <appender-ref ref="ACCESS_STDOUT"/>
</configuration>
```

Access logs are a little tricky because they don't support MDC, so I added a custom JSON provider above to inject a trace and span ID into the logs. I used this exact same approach on our other app using Play Framework, and it worked fine, but Tomcat wasn't part of the equation there.

This provider looks like:

```java
package com.example.logging.logback;

import ch.qos.logback.access.spi.IAccessEvent;
import com.fasterxml.jackson.core.JsonGenerator;
import datadog.trace.api.CorrelationIdentifier;
import java.io.IOException;
import java.util.HashMap;
import net.logstash.logback.composite.AbstractFieldJsonProvider;
import net.logstash.logback.composite.JsonWritingUtils;
import net.logstash.logback.encoder.AccessEventCompositeJsonEncoder;

public class DatadogTraceJsonProvider extends AbstractFieldJsonProvider<IAccessEvent> {

  public static final String FIELD_DATADOG = "dd";

  public DatadogTraceJsonProvider() {
    setFieldName(FIELD_DATADOG);
  }

  @Override
  public void writeTo(JsonGenerator generator, IAccessEvent iAccessEvent) throws IOException {
    final HashMap<String, String> traceIds = new HashMap<>();
    traceIds.put("trace_id", CorrelationIdentifier.getTraceId());
    traceIds.put("span_id", CorrelationIdentifier.getSpanId());
    JsonWritingUtils.writeMapStringFields(generator, getFieldName(), traceIds);
  }

}
```

When I start my app, the problem is that while I do see trace_id and span_id injected into the access logs, the IDs are always 0. Note that -Ddd.logs.injection=true is being passed in and I can confirm that normal application logs (vs these access logs) do have identifiers for each entry. My best guess is that the correlation IDs aren't initialized when Logback Access sees the request / response, but I'm not super familiar with how all of that works. I've also filed a support ticket, but was hoping somebody here would have some more insight about the inner workings of the agent.

Is there a way for me to restructure things to get access logs working with correlation identifiers?

**Comment by tylerbenson** [comment]
Could you provide a stacktrace for when the access log is written?  I'm guessing that the trace either hasn't started yet or already finished when the log is written, thus I would expect the id's to be 0.

**Comment by wuservices** [comment]
Thanks for taking a look. Here's a stacktrace that I added where I capture the trace IDs in the `writeTo` method above. I believe since this has to also log the response, it runs after the trace is over, at which point the IDs are 0 as you mentioned.

I also turned on debug logging so you can see this in the context of those logs, and formatted the logs a little for readability:

```
[dd.trace 2020-02-12 17:44:38:738 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.PendingTrace - traceId: 5570562189835279936 -- registered span DDSpan [ t_id=5570562189835279936, s_id=3812067430446888117, p_id=0] trace=.../servlet.request/servlet.request metrics={} tags={language=jvm, runtime-id=5541d121-7680-4ace-a5e4-5bee3e0f1bba, thread.id=91, thread.name=catalina-exec-5}, duration_ns=0. count = 1
[dd.trace 2020-02-12 17:44:38:738 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.DDTracer - Starting a new span: DDSpan [ t_id=5570562189835279936, s_id=3812067430446888117, p_id=0] trace=.../servlet.request/servlet.request metrics={} tags={language=jvm, runtime-id=5541d121-7680-4ace-a5e4-5bee3e0f1bba, thread.id=91, thread.name=catalina-exec-5}, duration_ns=0
[dd.trace 2020-02-12 17:44:38:762 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.DDSpan - Finished: DDSpan [ t_id=5570562189835279936, s_id=3812067430446888117, p_id=0] trace=.../servlet.request/GET /static/? metrics={_dd1.sr.eausr=1.0} tags={component=java-web-servlet, http.method=GET, http.status_code=304, http.url=https://dev.example.com/static/favicon-192x192.png, language=jvm, peer.hostname=127.0.0.1, peer.ipv4=127.0.0.1, peer.port=44984, runtime-id=5541d121-7680-4ace-a5e4-5bee3e0f1bba, servlet.path=/static/favicon-192x192.png, span.kind=server, span.origin.type=org.apache.catalina.core.ApplicationFilterChain, thread.id=91, thread.name=catalina-exec-5}, duration_ns=24119304
[dd.trace 2020-02-12 17:44:38:762 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.PendingTrace - Writing 1 spans to DDAgentWriter { api=DDApi { tracesUrl=http://localhost:8126/v0.4/traces }, monitor=StatsD { host=localhost:8125 } }.
[dd.trace 2020-02-12 17:44:38:763 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - DDSpan [ t_id=5570562189835279936, s_id=3812067430446888117, p_id=0] trace=.../servlet.request/GET /static/? metrics={_dd1.sr.eausr=1.0} tags={component=java-web-servlet, http.method=GET, http.status_code=304, http.url=https://dev.example.com/static/favicon-192x192.png, language=jvm, peer.hostname=127.0.0.1, peer.ipv4=127.0.0.1, peer.port=44984, runtime-id=5541d121-7680-4ace-a5e4-5bee3e0f1bba, servlet.path=/static/favicon-192x192.png, span.kind=server, span.origin.type=org.apache.catalina.core.ApplicationFilterChain, thread.id=91, thread.name=catalina-exec-5}, duration_ns=24119304 - Span is sampled: true
[dd.trace 2020-02-12 17:44:38:763 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.DDSpanContext - Set sampling priority to 1
[dd.trace 2020-02-12 17:44:38:764 +0000] [catalina-exec-5] DEBUG datadog.trace.agent.ot.PendingTrace - traceId: 5570562189835279936 -- Expired reference. count = 0
{
  "@timestamp": "2020-02-12T17:44:38.765Z",
  "@version": "1",
  "message": "Stack trace from where we're logging access logs",
  "logger_name": "com.example.logging.logback.DatadogTraceJsonProvider",
  "thread_name": "catalina-exec-5",
  "level": "ERROR",
  "level_value": 40000,
  "stack_trace": java.lang.Exception: This is where trace IDs are coming from
                    at com.example.logging.logback.DatadogTraceJsonProvider.writeTo(DatadogTraceJsonProvider.java:38)
                    at com.example.logging.logback.DatadogTraceJsonProvider.writeTo(DatadogTraceJsonProvider.java:21)
                    at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)
                    at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:188)
                    at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:165)
                    at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:122)
                    at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:34)
                    at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
                    at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
                    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
                    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
                    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:268)
                    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
                    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
                    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
                    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
                    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
                    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                    at java.lang.Thread.run(Thread.java:748)
,
  "source": "java",
  "sourcecategory": "application"
}
{
  "@timestamp": "2020-02-12T17:44:38.764Z",
  "@version": "1",
  "method": "GET",
  "protocol": "HTTP/1.1",
  "status_code": 304,
  "requested_url": "GET /static/favicon-192x192.png HTTP/1.1",
  "requested_uri": "/static/favicon-192x192.png",
  "remote_host": "127.0.0.1",
  "content_length": -1,
  "elapsed_time": 28,
  "request_headers": {
    ...,
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
  },
  "response_headers": {
    ...,
    "last-modified": "Fri, 06 Sep 2019 11:26:16 GMT"
  },
  "dd": {
    "trace_id": "0",
    "span_id": "0"
  },
  "source": "java",
  "sourcecategory": "access"
}
[dd.trace 2020-02-12 17:44:39:165 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.writer.ddagent.DDAgentApi - Successfully sent 1 of 2 traces to the DD agent.
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.sampling.RateByServiceSampler - Update service sampler rates: http://localhost:8126/v0.4/traces -> {"rate_by_service":{"service:,env:":1,"[tags omitted...]":1,"[tags omitted...]":1,"[tags omitted...]":1}}
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - Initializing the RateSampler, sampleRate: 100.0 %
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - Initializing the RateSampler, sampleRate: 100.0 %
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - Initializing the RateSampler, sampleRate: 100.0 %
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - Initializing the RateSampler, sampleRate: 100.0 %
[dd.trace 2020-02-12 17:44:39:166 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.writer.ddagent.TraceConsumer - Successfully sent 1 traces to the API```

Is there any way the trace context could persist until Tomcat was done or any way it could get passed down to this logger?

**Comment by randomanderson** [comment]
We're going to add trace id and span id as request attributes.  According to [this](http://logback.qos.ch/manual/layouts.html#AccessPatternLayout), they would be readable by logback by using `reqAttribute{dd.trace_id}` and `reqAttribute{dd.span_id}` in your pattern

**Comment by wuservices** [comment]
@randomanderson thanks adding this in! Is the thought that if I were using the sample code above, that in `DatadogTraceJsonProvider.writeTo()`, I could use `iAccessEvent.getRequest().getAttribute("dd.trace_id")` to get the trace ID?

**Comment by randomanderson** [comment]
@wuservices I think that should work.  You might not need to even have a custom JsonProvider anymore.  I believe logback has first-class support for request attributes in patterns. http://logback.qos.ch/manual/layouts.html#AccessPatternLayout .  I'm not 100% sure on this.

Closing this issue as the release is now out.  Please reopen or continue to comment if you need more help.

**Comment by wuservices** [comment]
@randomanderson you rock! Thanks for the pointer. Just wanted to confirm that you can just use the first-class support for request attributes in the pattern as you mentioned. 💯
