### ISSUE TITLE
When upgrading to v.0.41.0 AsyncHandlerWrapper (playws2) throws Exception

### ISSUE THREAD

**Issue by tanvn** [DataDog/dd-trace-java#1252]
We tried to upgrade from 0.31.2 to 0.41.0 last week. 
In our application, we are using play.api.libs.ws.StandaloneWSClient to call some GET http request.
When upgrading to 0.41.0, an IllegalStateException exception has been thrown out and we had to rollback to 0.31.2 version.
We are still unclear about the cause of the exception, so I created this issue so that if you guys have any clue, please share it with us.
Here is the stack trace 

```
Caused by: java.lang.IllegalStateException: Should not have received bodypart
	at play.api.libs.ws.ahc.DefaultStreamedAsyncHandler.onBodyPartReceived(Streamed.scala:64)
	at datadog.trace.instrumentation.playws2.AsyncHandlerWrapper.onBodyPartReceived(AsyncHandlerWrapper.java:34)
	at play.shaded.ahc.org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:108)
	at play.shaded.ahc.org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142)
	at play.shaded.ahc.org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at play.shaded.ahc.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at play.shaded.ahc.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at play.shaded.ahc.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by randomanderson** [comment]
What version of Play-WS are you using "2"?  And what version of scala?

**Comment by tanvn** [comment]
thank you for your reply.
We are using scala 2.13 with **play-ahc-ws-standalone** of version 2.0.8
Please let me know if you need any further information.

**Comment by tylerbenson** [comment]
I think a code snippet or a sample application of how you're using the library would be helpful.

**Comment by tanvn** [comment]
@tylerbenson thank you for you reply. I will prepare a sample application and share it with you guys soon.

**Comment by tanvn** [comment]
Hi @tylerbenson 
I just created a repository for a minimum sample application which could help you reproduce the exception (100% of the time)
Please take a look https://github.com/tanvn/play-ws-java-agent-debugger
I also add the steps to run the application and the main file is [PlayWsTestController](https://github.com/tanvn/play-ws-java-agent-debugger/blob/master/app/test/PlayWsTestController.scala)
Please let me know if you need any further information.

Cheers,

**Comment by tanvn** [comment]
In addition, the above repository sample code is very close to our application code. (Just added some updates today)
And with the sample code, we can confirm you that it works well with version 0.31.2 and throws exception with version 0.41.0 (100% of the time)
The thrown exception is making the API return **500 Internal Server Error** 
So if you guys have any clue or information, please let us know.
We are more than happy to create a Pull request for this issue.

Best regards,

**Comment by randomanderson** [comment]
To give an update, I was able to replicate the issue and fix it.  Testing revealed another bug that I am attempting to fix (child spans in `.transform()` callbacks aren't connected).  If I can't fix that bug easily, I'll create a pull request with just the first fix

**Comment by randomanderson** [comment]
The fix has been merged in and will be in the 0.46.0 release.  Thanks for pointing this out to us.

---

Separately, there were a couple of minor things that noticed with your test project that you might want to address:

- `dd-java-agent` should **_never_** be in your `libraryDependencies`.  Doing so adds all of its dependencies to your classpath.  In the test project, the agent's slf4j implementation was being used instead of play's
- `dd-trace-api` only needs to be a libraryDependency if your are using it.  If you're only doing autoinstrumentation, you probably don't need it
- The play instrumentation is enabled by default so you don't need to set `dd.integration.play.enabled`
- As of 0.34.0, setting `dd.trace.debug` automatically adjust the log level to debug so you don't need to set it via `datadog.slf4j.simpleLogger.defaultLogLevel`

**Comment by tanvn** [comment]
@randomanderson 
Thank you for dedicating your time and energy into this issue. 🎉
We will try upgrading to 0.46 when it is available and remove unnecessary dependencies !
Thanks again for this !

**Comment by randomanderson** [comment]
This change has been released.
