### ISSUE TITLE
MySQL and Custom Tracing lost after update to version 0.44.0

### ISSUE THREAD

**Issue by codylerum** [DataDog/dd-trace-java#1276]
Still receiving traces for http all other types such as mysql, aws, and custom via annotation appear to have stopped reporting.

Ubuntu 18.04
Java 13.0.2
Wildfly 18.0.1.Final

**Comment by trask** [comment]
Possibly related to #1275

**Comment by codylerum** [comment]
Also seems like this version broke postgres JDBC driver.

```
2020-03-02 03:01:06,925 WARN  [org.jboss.modules.define] (EJB default - 1) Failed to define class org.postgresql.jdbc.PgStatement$1 in Module "deployment.postgresql-42.2.5.jar" from Service Module Loader: java.lang.NoClas
sDefFoundError: Failed to link org/postgresql/jdbc/PgStatement$1 (Module "deployment.postgresql-42.2.5.jar" from Service Module Loader): datadog/trace/bootstrap/FieldBackedContextStoreAppliedMarker
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at deployment.postgresql-42.2.5.jar//org.postgresql.jdbc.PgConnection.createStatement(PgConnection.java:1216)
	at deployment.postgresql-42.2.5.jar//org.postgresql.jdbc.PgConnection.createStatement(PgConnection.java:1674)
	at deployment.postgresql-42.2.5.jar//org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:416)
	at deployment.postgresql-42.2.5.jar//org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:410)
	at deployment.postgresql-42.2.5.jar//org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:811)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.<init>(BaseWrapperManagedConnection.java:197)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnection.<init>(LocalManagedConnection.java:62)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:330)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConn
ectionPool.java:1328)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:
499)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:597)
	at org.jboss.ironjacamar.impl@1.4.17.Final//org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:151)
	at org.jboss.as.connector@18.0.1.Final//org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64)
```

**Comment by tylerbenson** [comment]
Fixed in https://github.com/DataDog/dd-trace-java/releases/tag/v0.45.0
