### ISSUE TITLE
DDAgentWriter blocking JVM shutdown

### ISSUE THREAD

**Issue by lyang** [DataDog/dd-trace-java#1376]
Hi,
We ran into an issue that the following exception prevented our application from shutting down.

```
Exception in thread \"dd-trace-disruptor\" java.lang.RuntimeException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@545630d6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4c3f2dd1[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 15]
! at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
! at com.lmax.disruptor.dsl.ExceptionHandlerWrapper.handleEventException(ExceptionHandlerWrapper.java:18)
! at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:187)
! at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
! at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@545630d6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4c3f2dd1[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 15]
! at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
! at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
! at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
! at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
! at datadog.trace.common.writer.DDAgentWriter.scheduleFlush(DDAgentWriter.java:272)
! at datadog.trace.common.writer.DDAgentWriter.access$1400(DDAgentWriter.java:43)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.reportTraces(DDAgentWriter.java:413)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:323)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:292)
! at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
! ... 2 more
com.lmax.disruptor.FatalExceptionHandler: Exception processing: 15 datadog.trace.common.writer.DDAgentWriter$Event@1131dd13
! java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@545630d6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4c3f2dd1[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 15]
! at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
! at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
! at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
! at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
! at datadog.trace.common.writer.DDAgentWriter.scheduleFlush(DDAgentWriter.java:272)
! at datadog.trace.common.writer.DDAgentWriter.access$1400(DDAgentWriter.java:43)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.reportTraces(DDAgentWriter.java:413)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:323)
! at datadog.trace.common.writer.DDAgentWriter$TraceConsumer.onEvent(DDAgentWriter.java:292)
! at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
! at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
! at java.lang.Thread.run(Thread.java:748)
```
I saw a very similar issue reported in #1145 and fixed in #1150, released in `0.40.0`

But we are seeing this again using `dd-agent-java 0.41.0`. It was the first time we saw this in a couple of months though.

**Comment by andrewsouthard1** [comment]
Hey @lyang - to confirm do you see this in the latest tracing client `0.62.0`?

**Comment by randomanderson** [comment]
Closing this as stale.  We've made numerous improvements to our threading and publishing pipelines.  LMAX Disruptor is no longer used by the tracer.  Please reopen if you find the same or similar issues with a more recent version
