### ISSUE TITLE
NullPointerException with Kafka-Streams

### ISSUE THREAD

**Issue by damienpalacio** [DataDog/dd-trace-java#1631]
Good evening,

Setting a Java service running on Kubernetes which use Kafka-Streams to load data from several topics. I'm facing issues with Datadog tracing feature. Here is the error. Seems header exists but has no values.
In other services we are using Kafka (not streams) we don't face such issue.

```
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.DDSpan - Started span: DDSpan [ t_id=8508458468495366505, s_id=634059728486302085, p_id=0] trace=app/kafka.consume/kafka.consume metrics={} tags={language=jvm, runtime-id=6b86f5de-e825-47b6-9688-92ea52293838, thread.id=44, thread.name=app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1}, duration_ns=0
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.PendingTrace - t_id=8508458468495366505 -> registered span DDSpan [ t_id=8508458468495366505, s_id=634059728486302085, p_id=0] trace=app/kafka.consume/kafka.consume metrics={} tags={language=jvm, runtime-id=6b86f5de-e825-47b6-9688-92ea52293838, thread.id=44, thread.name=app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1}, duration_ns=0. count = 1
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.DDSpan - Finished span: DDSpan [ t_id=8508458468495366505, s_id=634059728486302085, p_id=0] trace=kafka/kafka.consume/kafka.consume metrics={} tags={_dd.measured=true, component=java-kafka, language=jvm, offset=301674, partition=0, resource.name=Consume Topic input.topic, runtime-id=6b86f5de-e825-47b6-9688-92ea52293838, span.kind=consumer, span.type=queue, thread.id=44, thread.name=app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1}, duration_ns=51943
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.PendingTrace - Writing 1 spans to DDAgentWriter { api=DDApi { tracesUrl=http://server_url/v0.4/traces } }.
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.common.sampling.DeterministicSampler - DDSpan [ t_id=8508458468495366505, s_id=634059728486302085, p_id=0] trace=kafka/kafka.consume/kafka.consume metrics={} tags={_dd.measured=true, component=java-kafka, language=jvm, offset=301674, partition=0, resource.name=Consume Topic input.topic, runtime-id=6b86f5de-e825-47b6-9688-92ea52293838, span.kind=consumer, span.type=queue, thread.id=44, thread.name=app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1}, duration_ns=51943 - Span is sampled: false
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.DDSpanContext - Set sampling priority to 0
[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] DEBUG datadog.trace.agent.core.PendingTrace - t_id=8508458468495366505 -> expired reference. count=0 spans=0 continuations=0

[dd.trace 2020-06-25 16:33:54:565 +0000] [app-3044765435123869542-3630405a-4693-4a0f-bbea-1a4fe42d3bba-StreamThread-1] ERROR datadog.trace.agent.core.propagation.DatadogHttpCodec - Exception when extracting context
java.lang.NullPointerException
	at java.base/java.lang.String.<init>(Unknown Source)
	at datadog.trace.instrumentation.kafka_streams.TextMapExtractAdapter.get(TextMapExtractAdapter.java:29)
	at datadog.trace.instrumentation.kafka_streams.TextMapExtractAdapter.get(TextMapExtractAdapter.java:10)
	at datadog.trace.agent.core.propagation.DatadogHttpCodec$Extractor.extract(DatadogHttpCodec.java:73)
	at datadog.trace.agent.core.propagation.HttpCodec$CompoundExtractor.extract(HttpCodec.java:95)
	at datadog.trace.agent.core.CoreTracer.extract(CoreTracer.java:332)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.nextRecord(PartitionGroup.java:142)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:417)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:474)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:536)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:792)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:698)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:671)
  ```

Libraries used:
// Kafka
        implementation 'org.apache.kafka:kafka-streams:2.4.1'
        implementation 'org.apache.kafka:kafka-clients:2.4.1'
        testImplementation 'org.apache.kafka:kafka-streams-test-utils:2.4.1'
// DataDog
        implementation 'com.datadoghq:dd-trace-api:0.55.1'
        implementation 'com.datadoghq:java-dogstatsd-client:2.10.1'

**Comment by richardstartin** [comment]
@damienpalacio thanks for the report - we'll get this fixed ASAP. To help me reproduce, can you tell me more about the _producer_ of the traced record? Is it using the kafka-streams integration or the kafka-clients integration?

**Comment by damienpalacio** [comment]
a null check here would solve the issue, but doesn't explain why it happens:
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/TextMapExtractAdapter.java#L29

**Comment by richardstartin** [comment]
@damienpalacio thanks, and yes we will fix the cause not the symptom.

**Comment by damienpalacio** [comment]
so I modified TextMapExtractAdapter.java in both kafka_streams and kafka_clients, and now it works (no more exception, and we have tracing on endpoints).

**Comment by damienpalacio** [comment]
Ah yes you are right I had to go through a Fork for that! Here is the PR: https://github.com/DataDog/dd-trace-java/pull/1650

**Comment by damienpalacio** [comment]
PR merged. Closing the issue!
