### ISSUE TITLE
Datadog agent is not allowing proxool library to establish connection

### ISSUE THREAD

**Issue by neomatrix1993** [DataDog/dd-trace-java#1634]
So I am trying to intergrate datadog with a service, when I see this:
Notes:
- also the service runs properly without dd agent enabled, but when its enabled, I see this stack trace below
- I also added debugger to see the depths and where it could be breaking, but couldn't really get to some understanding.
- Agent: latest, only apm was enabled (dd-java-agent.jar)
- Service: vertx, open-jdk 8
- Apparently the issue comes, when a particular library called proxool-cglib.jar is trying to establish connection to database.

The error stack:
```
quickfix.ConfigError: error during session initialization
	at quickfix.mina.initiator.AbstractSocketInitiator.createSessions(AbstractSocketInitiator.java:198)
	at quickfix.mina.initiator.AbstractSocketInitiator.createSessionInitiators(AbstractSocketInitiator.java:80)
	at quickfix.SocketInitiator.initialize(SocketInitiator.java:117)
	at quickfix.SocketInitiator.start(SocketInitiator.java:111)
	-- hidden
	at io.vertx.core.Future.lambda$map$4(Future.java:402)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$getConfig$2(ConfigRetrieverImpl.java:182)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$compute$9(ConfigRetrieverImpl.java:296)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.CompositeFutureImpl.doComplete(CompositeFutureImpl.java:252)
	at io.vertx.core.impl.CompositeFutureImpl.tryComplete(CompositeFutureImpl.java:227)
	at io.vertx.core.impl.CompositeFutureImpl.tryComplete(CompositeFutureImpl.java:232)
	at io.vertx.core.impl.CompositeFutureImpl.complete(CompositeFutureImpl.java:199)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$0(CompositeFutureImpl.java:39)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$null$6(ConfigRetrieverImpl.java:266)
	at io.vertx.config.impl.ConfigurationProvider.lambda$null$0(ConfigurationProvider.java:83)
	at io.vertx.config.impl.spi.JsonProcessor.process(JsonProcessor.java:42)
	at io.vertx.config.impl.ConfigurationProvider.lambda$get$1(ConfigurationProvider.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.VerifyError: (class: org/postgresql/core/BaseStatement$$EnhancerByProxool$$fd4e323c, method: execute signature: ()Z) Register 1 contains wrong type
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.logicalcobwebs.cglib.proxy.Enhancer.getCallbacksSetter(Enhancer.java:627)
	at org.logicalcobwebs.cglib.proxy.Enhancer.setCallbacksHelper(Enhancer.java:615)
	at org.logicalcobwebs.cglib.proxy.Enhancer.setThreadCallbacks(Enhancer.java:609)
	at org.logicalcobwebs.cglib.proxy.Enhancer.createUsingReflection(Enhancer.java:631)
	at org.logicalcobwebs.cglib.proxy.Enhancer.firstInstance(Enhancer.java:538)
	at org.logicalcobwebs.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:225)
	at org.logicalcobwebs.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.logicalcobwebs.cglib.proxy.Enhancer.create(Enhancer.java:285)
	at org.logicalcobwebs.proxool.ProxyFactory.getProxy(ProxyFactory.java:116)
	at org.logicalcobwebs.proxool.ProxyFactory.getStatement(ProxyFactory.java:97)
	at org.logicalcobwebs.proxool.WrappedConnection.invoke(WrappedConnection.java:196)
	at org.logicalcobwebs.proxool.WrappedConnection.intercept(WrappedConnection.java:87)
	at org.postgresql.PGConnection$$EnhancerByProxool$$80c2df73.prepareStatement(<generated>)
	at quickfix.JdbcStore.loadCache(JdbcStore.java:126)
	at quickfix.JdbcStore.<init>(JdbcStore.java:86)
	at quickfix.JdbcStoreFactory.create(JdbcStoreFactory.java:45)
	at quickfix.Session.<init>(Session.java:503)
	at quickfix.DefaultSessionFactory.create(DefaultSessionFactory.java:209)
	at quickfix.mina.SessionConnector.createSession(SessionConnector.java:182)
	at quickfix.mina.initiator.AbstractSocketInitiator.createSessions(AbstractSocketInitiator.java:191)
	... 38 more
```
I am not sure how to fix this issue, as there is not much content available online, and so if datadog has already faced something like this, please do let me know. Would be very helpful.

**Comment by richardstartin** [comment]
@neomatrix1993 which version of the tracer are you using?

**Comment by neomatrix1993** [comment]
@richardstartin as I mentioned its the latest agent download from the web.
Downloaded this :
'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST'
And added to docker base image. Is that what you meant?

**Comment by devinsba** [comment]
@neomatrix1993 can you please clarify the exact version of `dd-trace-java.jar` you are using? We thought this issue was fixed in 0.54.0 via #1524

**Comment by neomatrix1993** [comment]
@devinsba I checked, its 0.53

**Comment by neomatrix1993** [comment]
@devinsba thanks a lot. The application is able to start now. 🙏🏻
