### ISSUE TITLE
UnsupportedOperationException from MDC

### ISSUE THREAD

**Issue by aarya123** [DataDog/dd-trace-java#1647]
I suspect it was caused by https://github.com/DataDog/dd-trace-java/pull/1579, and at a quick guess, https://github.com/DataDog/dd-trace-java/pull/1579/files#diff-ddc855d905a56896d1c42dfd404e8541R67.
Basically, we can't put in our own data into the MDC anymore.
```java
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.put(LogbackMDCAdapter.java:110)
	at org.slf4j.MDC.put(MDC.java:147)
	at com.hulu.service.heimdall.requests.RequestIds.saveRequestId(RequestIds.java:74)
	at com.hulu.service.heimdall.handlers.RequestIdExtractor.handle(RequestIdExtractor.java:25)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at com.hulu.service.heimdall.handlers.CorsHandler.handle(CorsHandler.java:104)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at com.hulu.module.diagnostics.logging.ratpack.DefaultNcsaRequestLogger.handle(DefaultNcsaRequestLogger.java:56)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.handling.internal.OnlyIfHandler.handle(OnlyIfHandler.java:38)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at datadog.trace.instrumentation.ratpack.TracingHandler.handle(TracingHandler.java:61)
	at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:157)
	at ratpack.handling.internal.DefaultContext.lambda$start$4(DefaultContext.java:104)
	at ratpack.exec.internal.DefaultExecution.lambda$new$0(DefaultExecution.java:82)
	at ratpack.exec.internal.DefaultExecution$InitialExecStream.exec(DefaultExecution.java:403)
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:224)
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:217)
	at ratpack.exec.internal.DefaultExecution.lambda$exec$4(DefaultExecution.java:215)
	at ratpack.logging.MDCInterceptor.intercept(MDCInterceptor.java:196)
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:215)
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:187)
	at ratpack.exec.internal.DefaultExecController$1.start(DefaultExecController.java:191)
	at ratpack.handling.internal.DefaultContext.start(DefaultContext.java:101)
	at ratpack.server.internal.NettyHandlerAdapter.newRequest(NettyHandlerAdapter.java:183)
	at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMess...```

**Comment by richardstartin** [comment]
@aarya123 thanks for the report - we're getting this fixed ASAP.

**Comment by aarya123** [comment]
Any case this can/should be release as 0.56.1?
