### ISSUE TITLE
java.lang.NoClassDefFoundError jdk/jfr/Event on Java 8 

### ISSUE THREAD

**Issue by tamanugi** [DataDog/dd-trace-java#1672]
My Application has crash when boot....
I found following Error.

```
[dd.trace 2020-07-13 05:44:48:709 +0000] [main] INFO datadog.trace.bootstrap.Agent - Initializing JMX thread CPU time provider
[dd.trace 2020-07-13 05:44:48:711 +0000] [main] INFO datadog.trace.bootstrap.Agent - Initializing JMX thread deadlock detector
[dd.trace 2020-07-13 05:44:48:715 +0000] [main] ERROR datadog.trace.bootstrap.Agent - Throwable thrown while initializing JMX thread deadlock detector
java.lang.NoClassDefFoundError: jdk/jfr/Event
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at datadog.trace.bootstrap.DatadogClassLoader$DelegateClassLoader.loadClass(DatadogClassLoader.java:161)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.datadog.profiling.controller.openjdk.events.DeadlockEventFactory.<clinit>(DeadlockEventFactory.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.Agent.registerDeadlockDetectionEvent(Agent.java:278)
        at datadog.trace.bootstrap.Agent.startJmx(Agent.java:267)
        at datadog.trace.bootstrap.Agent.start(Agent.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:57)
        at datadog.trace.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: jdk.jfr.Event
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at datadog.trace.bootstrap.DatadogClassLoader.loadFromPackage(DatadogClassLoader.java:74)
        at datadog.trace.bootstrap.DatadogClassLoader$DelegateClassLoader.loadClass(DatadogClassLoader.java:163)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

### dd-trace

```
[dd.trace 2020-07-13 05:44:49:900 +0000] [main] INFO datadog.trace.agent.tooling.VersionLogger - dd-trace-core - version: 0.57.0~58cf75de6
[dd.trace 2020-07-13 05:44:49:903 +0000] [main] INFO datadog.trace.agent.tooling.VersionLogger - dd-trace-api - version: 0.57.0~58cf75de6
[dd.trace 2020-07-13 05:44:49:904 +0000] [main] INFO datadog.trace.agent.tooling.VersionLogger - dd-java-agent - version: 0.57.0~58cf75de6

```

### Java

```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

## SystemProperty

```
-javaagent:$$lib_dir/dd-java-agent.jar
-Ddd.trace.analytics.enabled=true
-Ddd.trace.global.tags=env:$$APPLICATION_ENVIRONMENT
-Ddd.logs.injection=true
-Ddd.service.name=xxx
-Ddd.http.server.tag.query-string=true
```

**Comment by richardstartin** [comment]
Hi @tamanugi this stack trace is a little misleading and won't be crashing your application, the message when JFR is not found was made friendlier in #1666.

**Comment by tamanugi** [comment]
@richardstartin 

Thank you for reply!

Sorry, It seems that a few coincidences have led me to mistakenly believe that this message was the cause 🙇 
It's a nice change for us to have a friendlier message!!
