### ISSUE TITLE
ConcurrentModificationException in MDC after upgrading to 0.59

### ISSUE THREAD

**Issue by theigl** [DataDog/dd-trace-java#1753]
I just upgraded from 0.58 to 0.59 and I frequently see these exceptions now:

```
  java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1524)
        at java.base/java.util.HashMap.putMapEntries(HashMap.java:507)
        at java.base/java.util.HashMap.<init>(HashMap.java:485)
        at ch.qos.logback.classic.util.LogbackMDCAdapter.getCopyOfContextMap(LogbackMDCAdapter.java:189)
        at org.slf4j.MDC.getCopyOfContextMap(MDC.java:248)
        at com.myproject.base.util.executor.MDCExecutorService.wrapTask(MDCExecutorService.java:24)
        at com.myproject.base.util.executor.WrappingExecutorService.submit(WrappingExecutorService.java:54)
        at com.myproject.base.util.executor.WrappingExecutorService.submit(WrappingExecutorService.java:54)
        at io.micrometer.core.instrument.internal.TimedExecutorService.submit(TimedExecutorService.java:77)
        at org.springframework.core.task.support.TaskExecutorAdapter.submit(TaskExecutorAdapter.java:127)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:290)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:129)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
```

MDCExecutorService looks like this:

```
  @Slf4j
  public final class MDCExecutorService extends WrappingExecutorService {

	public MDCExecutorService(ExecutorService delegate) {
		super(delegate);
	}

	@Override
	protected <T> Callable<T> wrapTask(Callable<T> callable) {
		final Map<String, String> context = MDC.getCopyOfContextMap();
		return new MDCCallable<>(callable, context);
	}

	@RequiredArgsConstructor
	private static class MDCCallable<T> implements Callable<T> {

		@NonNull
		private final Callable<T> delegate;
		private final Map<String, String> context;

		@Override
		public T call() throws Exception {
			if (context == null) {
				MDC.clear();
			} else {
				MDC.setContextMap(context);
			}
			try {
				return delegate.call();
			} finally {
				MDC.clear();
			}
		}
	}
  }
```

Possibly related to #1688.

**Comment by lpriima** [comment]
Hi @theigl , 
Did you use set `-Ddd.logs.injection=true` ? It should be `false` bu default. Could you please provide command line how you start your application ?

**Comment by theigl** [comment]
@lpriima: Yes. 

These are my DD arguments:

```
  -Ddd.service.name=myService
  -Ddd.trace.enabled=true
  -Ddd.trace.debug=false
  -Ddatadog.slf4j.simpleLogger.logFile=logDir/datadog_tracer.log
  -Ddd.trace.analytics.enabled=false
  -Ddd.trace.global.tags=env:prod
  -Ddd.trace.split-by-tags=true
  -Ddd.trace.db.client.split-by-instance=true
  -Ddd.logs.injection=true
  -Ddd.jdbc.analytics.enabled=false
  -Ddd.jmxfetch.enabled=true
  -Ddd.jmxfetch.check-period=5000
  -Ddd.profiling.enabled=true
  -Ddd.profiling.jfr-template-override-file=appDir/dd-overrides.jfp
```

**Comment by lpriima** [comment]
@theigl ,

1. could you please also confirm version of java11, logback, spring and micrometer versions you are using ?
1. do you run your app with 2 `-javaagent` arguments? Could you please also provide the whole command line ?

**Comment by theigl** [comment]
@lpriima:

- OpenJDK 11.0.8 
- Logback 1.2.3
- Spring 5.2.8.RELEASE
- Micrometer 1.5.3

I'm not using any other agents:

    JAVA_OPTS="-Xmx8g -Xms8g -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=60 -XX:MaxGCPauseMillis=250 -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:FlightRecorderOptions=stackdepth=128 -Xlog:gc*:file=/opt/project/logs/gc-`date +%F_%H-%M-%S`.log::filecount=10,filesize=10M -Xlog:ergo*=trace -Xlog:age*=trace -XX:ErrorFile=/opt/project/logs/hs_err_pid%p.log -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/project/logs/`date +%F_%H-%M-%S`.hprof -javaagent:/data/datadog/dd-java-agent.jar -Ddd.service.name=project -Ddd.trace.enabled=true -Ddd.trace.debug=true -Ddatadog.slf4j.simpleLogger.logFile=/opt/project/logs/datadog_tracer.log -Ddd.trace.analytics.enabled=false -Ddd.trace.global.tags=env:prod -Ddd.trace.split-by-tags=true -Ddd.trace.db.client.split-by-instance=true -Ddd.logs.injection=true -Ddd.jdbc.analytics.enabled=false -Ddd.jmxfetch.enabled=true -Ddd.jmxfetch.check-period=5000 -Ddd.profiling.enabled=true -Ddd.profiling.jfr-template-override-file=/opt/project/dd-overrides.jfp

**Comment by theigl** [comment]
The error didn't happen for every new task. There seems to be some kind of timing issues.

**Comment by PHameete** [comment]
Same here after upgrading from 0.52.0 (0.55.0 also gave us issues, so skipped a few version):

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap.putMapEntries(Unknown Source)
	at java.base/java.util.HashMap.<init>(Unknown Source)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.getCopyOfContextMap(LogbackMDCAdapter.java:189)
	at org.slf4j.MDC.getCopyOfContextMap(MDC.java:248)
	at com.blockbax.coreapi.controller.ControllerUtil.getMDCHeaderContents(ControllerUtil.java:51)
	at com.blockbax.coreapi.interceptor.MDCInterceptor.postHandle(MDCInterceptor.java:80)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPostHandle(HandlerExecutionChain.java:161)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1047)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
...
```

The only non-standard parameter we use for launching is `-Ddatadog.slf4j.simpleLogger.defaultLogLevel=error`

**Comment by PHameete** [comment]
@lpriima Hi, sorry I overlooked this. All our service containers have DD_LOGS_INJECTION env var set to 'true'.

So logs injection is indeed enabled. But we do want datadog trace and span ids injected - can we still use this configuration? Is it a bug or should we configure this behavior differently?

**Comment by lpriima** [comment]
@PHameete , 
For now, trace, span ids and not scope related tags are injected by one property ( DD_LOGS_INJECTION ) 

It looks like we can go into body of static method of the class before instrumentation of <clinit> of the same class is completed. I've added explicit synchronisation: https://github.com/DataDog/dd-trace-java/issues/1753

**Comment by theigl** [comment]
@lpriima: I'm still getting the same `ConcurrentModificationException` with tracer version 0.60.

**Comment by theigl** [comment]
@lpriima: Since this still isn't working for me, is there any way to disable MDC injection for executors?

**Comment by lpriima** [comment]
@theigl I will do a flag. Is it the same stack trace or different after updating to 0.60.0/0.60.1 ? Could you please post it ?

**Comment by theigl** [comment]
@lpriima: I'm 99% sure it was the same stacktrace. The problem is that I immediately downgraded to 0.55 after I saw the exceptions and didn't copy the trace.

Thanks for resolving this so quickly!

**Comment by lpriima** [comment]
this feature is disabled by default in latest release: https://github.com/DataDog/dd-trace-java/releases/tag/v0.61.0 . Feel free to upgrade.


Instrumentation in class initialisation order seems to be fine: https://github.com/raphw/byte-buddy/issues/912 , but I will continue investigation why it might have happen.
