### ISSUE TITLE
UnsupportedOperationException from MDC

### ISSUE THREAD

**Issue by aniketkalamkar** [DataDog/dd-trace-java#1860]
When using datadog with MDC logging in springboot apps. We are getting below error - Due to this we are not able to use datadog for our application
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.put(LogbackMDCAdapter.java:110)
	at org.slf4j.MDC.put(MDC.java:147)
	at com.m.s.requests.RequestIds.saveRequestId(LogFilter.java:74)

**Comment by randomanderson** [comment]
What version of the tracer are you using? I believe this particular bug was fixed with #1645 (version 0.57.0)

**Comment by randomanderson** [comment]
Closing as resolved.  Please reopen if you still have issues after upgrading.
