### ISSUE TITLE
Atlassian Confluence fails to start when using trace-agent 0.71.0

### ISSUE THREAD

**Issue by fischaz** [DataDog/dd-trace-java#2317]
Hi team, 

My apologies for the ticket, I tried to look at the entire dd-trace-java source code and in a recent, similar issue, I managed to fix some loading issues in bamboo using `-Ddd.integration.runnable-future.enabled=false` ... but in this case, I'm out of ideas...

Versions:
 - atlassian confluence server 7.10.1
 - java OpenJDK 11
```
$ java -version
NOTE: Picked up JDK_JAVA_OPTIONS: --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/
java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-open
s=jdk.management/com.sun.management.internal=ALL-UNNAMED
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)
```
 - arch: x86_64
 - OS: linux (debian buster)

Error at startup:
```
[dd.trace 2021-01-20 23:01:57:293 +0000] [FelixStartLevel] ERROR datadog.trace.agent.tooling.HelperInjector - Error preparing helpers while processing class org.springframework.beans.factory.support.DefaultListableBeanFactory for BeanFactoryInstrumentation. Failed to inject helper classes into instance org.apache.servicemix.bundles.spring-beans [12]
java.lang.IllegalStateException: Error invoking (accessor)::defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:922)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
	at datadog.trace.agent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:171)
	at datadog.trace.agent.tooling.HelperInjector.transform(HelperInjector.java:119)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10364)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10761)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10699)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10258)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2410)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2194)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:197)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:127)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$301(AbstractDelegatedExecutionApplicationContext.java:57)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$1.run(AbstractDelegatedExecutionApplicationContext.java:165)
	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.normalRefresh(AbstractDelegatedExecutionApplicationContext.java:161)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$NoDependenciesWaitRefreshExecutor.refresh(AbstractDelegatedExecutionApplicationContext.java:75)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
	at org.eclipse.gemini.blueprint.extender.internal.support.ExtenderConfiguration.start(ExtenderConfiguration.java:164)
	at org.eclipse.gemini.blueprint.extender.internal.boot.ChainActivator.start(ChainActivator.java:93)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/filter/OncePerRequestFilter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.lang.ClassLoader$ByteBuddyAccessor$B29gl9Xi.defineClass(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:918)
	... 45 more
Caused by: java.lang.ClassNotFoundException: org.springframework.web.filter.OncePerRequestFilter not found by org.apache.servicemix.bundles.spring-beans [12]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
```

(this effectively block confluence to load plugins and start) - Current workaround is only to disable entirely the datadog APM trace agent (for now).

Although I have not entirely looked at the combination, I suspect this is probably more of a recent change in confluence than the datadog trace agent, but nonetheless, I'd like to fix the issue.

Would you be able to point me to anything or what would be my next step in trying to resolve this issue? I search the code in the hope of finding a way to exclude this class loader from being intercepted by datadog, but I have not found that argument or code (although I feel that the file `dd-java-agent\agent-tooling\src\main\java\datadog\trace\agent\tooling\bytebuddy\matcher\AdditionalLibraryIgnoresMatcher.java` might be close to what I want...

Thank you!

**Comment by mcculls** [comment]
Hi @fischaz we have a number of improvements for OSGi-based systems like Confluence that are targeting the next release of the tracer.

**Comment by fischaz** [comment]
Hi @mcculls , Looking forward to that :) 

Would you happen to know a rough ETA or target version for this new feature to be released? and would there be any workaround available for me to continue to use 'partially' the agent for now (or disabling is really the only way for now)?

**Comment by andrewsouthard1** [comment]
Hey @fischaz - we released these in 0.73.0 of the tracer. Can you confirm whether you are still seeing this issue?

**Comment by fischaz** [comment]
I'll give it a try this week if time allows at work :)

**Comment by fischaz** [comment]
Initial testing with Atlassian confluence (same docker image, just changed datadog trace agent) is looking good and I no longer see the Exception at all. 

I'll check and confirm a few WARNING message to be sure, but we should be able to close this issue :)
