### ISSUE TITLE
WildFly frequently fail to start when using dd-java-agent

### ISSUE THREAD

**Issue by bonivi** [DataDog/dd-trace-java#2399]
When a dd-java-agent was added to WildFly, quite frequently (e.g 3 times from 10 wildfly service restarts) the startup of Wildfly failed.

Evnironment:
  OS: Amazon Linux 2
  Java: Amazon Corretto 8u202
  Wildfly: 10.1.0.Final
  dd-java-agent: 0.72
  
```Starting WildFly application server...
=========================================================================
JBoss Bootstrap Environment
JBOSS_HOME: /opt/app/wildfly
JAVA: /opt/app/java/bin/java
JAVA_OPTS:  -server -Xms1024m -Xmx6144m -XX:MetaspaceSize=2048M -XX:MaxMetaspaceSize=6144m -Djava.net.preferIPv4Stack=true -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:/opt/app/wildfly/standalone/log/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/app/wildfly/standalone/log/heapdump.hprof -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -javaagent:/opt/datadog-agent/dd-java-agent.jar -Ddd.service.name=wildfly-perftest3 -Ddd.trace.global.tags=env:perftest3 -Ddd.trace.report-hostname=true
=========================================================================
[dd.trace 2021-02-08 09:19:50:162 +0000] [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.72.0~35c28f509","os_name":"Linux","os_version":"4.14.165-133.209.amzn2.x86_64","architecture":"amd64","lang":"jvm","lang_version":"1.8.0_202","jvm_vendor":"Amazon.com Inc.","jvm_version":"25.202-b08","java_class_version":"52.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"wildfly-perftest3","agent_url":"http://localhost:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":false,"profiling_enabled":false,"dd_version":"0.72.0~35c28f509","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"2287853d-f8b1-4d62-89e6-4417d0b66bbe","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false}}
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.NullPointerException
at java.util.logging.LogManager$1.run(LogManager.java:195)
at java.util.logging.LogManager$1.run(LogManager.java:181)
at java.security.AccessController.doPrivileged(Native Method)
at java.util.logging.LogManager.<clinit>(LogManager.java:181)
at java.util.logging.Logger.demandLogger(Logger.java:448)
at java.util.logging.Logger.getLogger(Logger.java:502)
at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
at javax.management.NotificationBroadcasterSupport.<clinit>(NotificationBroadcasterSupport.java:365)
at javax.management.MBeanServerDelegate.<init>(MBeanServerDelegate.java:72)
at com.sun.jmx.mbeanserver.MBeanServerDelegateImpl.<init>(MBeanServerDelegateImpl.java:100)
at com.sun.jmx.mbeanserver.JmxMBeanServer.newMBeanServerDelegate(JmxMBeanServer.java:1374)
at javax.management.MBeanServerBuilder.newMBeanServerDelegate(MBeanServerBuilder.java:66)
at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:321)
at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:469)
at datadog.trace.bootstrap.Agent.startJmx(Agent.java:292)
at datadog.trace.bootstrap.Agent.access$100(Agent.java:28)
at datadog.trace.bootstrap.Agent$StartJmxCallback.execute(Agent.java:194)
at datadog.trace.bootstrap.Agent$ClassLoadCallBack$1.run(Agent.java:168)
at java.lang.Thread.run(Thread.java:748)
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
Feb 08, 2021 9:19:55 AM org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.2.6.Final
Feb 08, 2021 9:19:56 AM org.jboss.as.server.ApplicationServerService start
INFO: WFLYSRV0049: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) starting
Feb 08, 2021 9:20:06 AM org.jboss.as.controller.AbstractOperationContext executeStep
ERROR: WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([])
java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.logging
at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:467)
at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387)
at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349)
at org.jboss.as.server.ServerService.boot(ServerService.java:397)
at org.jboss.as.server.ServerService.boot(ServerService.java:366)
at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
... 11 more
Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:147)
at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:131)
at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Feb 08, 2021 9:20:06 AM org.jboss.as.server.ServerService$4 logExit
FATAL: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
wildfly.service: main process exited, code=exited, status=1/FAILURE
Unit wildfly.service entered failed state.
wildfly.service failed.
```

**Comment by mcculls** [comment]
Hi @bonivi - can you try setting the following system property on the command-line used to launch the server:
```
-Ddd.app.customlogmanager=true
```
if you still see the exception then can you try adding:
```
-Ddd.app.customjmxbuilder=true
```
we also have some JMX related improvements scheduled for the next release that should help in this situation.

**Comment by codylerum** [comment]
FYI this happened to me on a server after trying to downgrade dd-java-agent.jar from 0.74.1 to 0.72.0 or 0.71.0.

the only way to get the server to start again was to take Datadog back to 0.74.1. Is something being written to disk by the agent that can't be read or ignored by older agent jars.

**Comment by mcculls** [comment]
Nothing is written to disk, it's just that 0.74.1 contains some additional JMX related improvements that help when tracing Wildfly applications (basically Wildfly wants to set a custom JMX builder, but only sets the system property to do this later on in its startup - so we need to delay any access to JMX until after the Wildfly JMX builder is registered.)

0.72.0 and 0.71.0 don't contain these JMX improvements which is why you may see this sort of issues with those versions - in which case setting the system properties above may help.

**Comment by mcculls** [comment]
The [0.75.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.75.0) release includes various fixes to help with this. Could you try that release and let us know if it still happens?
