### ISSUE TITLE
Opentracing initializtion failed at runitime

### ISSUE THREAD

**Issue by Ravenow** [DataDog/dd-trace-java#2767]
Hi I have pretty strange issue, with datadog java libs as of 0.63+ I have runtime errors with following code:

```
import datadog.opentracing.DDTracer

DDTracer.builder().build()

```

Error is:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'void datadog.trace.api.IOLogger.<init>(org.slf4j.Logger)'
	at datadog.trace.core.monitor.DDAgentStatsDConnection.<clinit>(DDAgentStatsDConnection.java:22)
	at datadog.trace.core.monitor.DDAgentStatsDClientManager.getConnection(DDAgentStatsDClientManager.java:66)
	at datadog.trace.core.monitor.DDAgentStatsDClientManager.statsDClient(DDAgentStatsDClientManager.java:58)
	at datadog.trace.core.CoreTracer.createStatsDClient(CoreTracer.java:710)
	at datadog.trace.core.CoreTracer.<init>(CoreTracer.java:365)
	at datadog.trace.core.CoreTracer.<init>(CoreTracer.java:64)
	at datadog.trace.core.CoreTracer$CoreTracerBuilder.build(CoreTracer.java:305)
	at datadog.opentracing.DDTracer.<init>(DDTracer.java:382)
	at datadog.opentracing.DDTracer.<init>(DDTracer.java:40)
	at datadog.opentracing.DDTracer$DDTracerBuilder.build(DDTracer.java:148)
	at example.Hello$.delayedEndpoint$example$Hello$1(Hello.scala:6)
	at example.Hello$delayedInit$body.apply(Hello.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at example.Hello$.main(Hello.scala:5)
	at example.Hello.main(Hello.scala)
```

Code sample - https://github.com/Ravenow/dd-ot-sample
import project to 'idea' and run 'Hello' object

**Comment by tylerbenson** [comment]
I loaded your project and was able to reproduce this locally.  The root cause of the problem is class conflicts between `dd-trace-ot` and `dd-trace-java` on your classpath.  You shouldn't ever need `dd-trace-java` on your classpath.  Right now the following is happening:
* DDAgentStatsDConnection is loaded from dd-trace-ot which doesn't use a shaded logger
* IOLogger class from dd-java-agent is being loaded which expects the shaded version of slf4j

This is why you're seeing that exception.  The constructor exists, but it's declared with the shaded type in that version of the class. If you remove `dd-java-agent` then it no longer fails.

**Comment by Ravenow** [comment]
Ok, i`ll put 'dd-java-agent' out of application classpath. Thanks
