### ISSUE TITLE
ClassCastException with Slick

### ISSUE THREAD

**Issue by Diagoras** [DataDog/dd-trace-java#325]
Using Slick 3.2.1, I see the following exceptions in the logs:

> Caused by: java.lang.ClassCastException: datadog.trace.instrumentation.java.concurrent.ExecutorInstrumentation$RunnableWrapper cannot be cast to slick.util.AsyncExecutor$PrioritizedRunnable
        at slick.util.ManagedArrayBlockingQueue.offer(ManagedArrayBlockingQueue.scala:13)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
        at slick.util.AsyncExecutor$$anon$2$$anon$3.execute(AsyncExecutor.scala:120)
        ...
        at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:231)
        at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:229)
        at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:208)
        at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:140)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.runInternal(BasicBackend.scala:76)
        at slick.basic.BasicBackend$DatabaseDef.runInternal$(BasicBackend.scala:75)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.run(BasicBackend.scala:73)
        at slick.basic.BasicBackend$DatabaseDef.run$(BasicBackend.scala:73)
        at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:37)

Looks like the Java APM agent is interfering with a cast that occurs in Slick. Let me know if you need any other details.

**Comment by tylerbenson** [comment]
Thanks for the report.  We'll look into it!
