### ISSUE TITLE
IllegalAccessError thrown from `AsyncAfterTransmissionInterceptorCallingResponseHandler`

### ISSUE THREAD

**Issue by gbiv** [DataDog/dd-trace-java#3398]
In a scala service that uses JDK 16 (adoptopenjdk/openjdk16:jre-16.0.1_9-alpine)  I'm seeing the following exception :
```bash
[dd.trace 2022-02-16 21:02:18:305 +0000] [BillingEventProcessor-akka.actor.default-dispatcher-25] DEBUG  
 datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for  
 software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler on  
 jdk.internal.loader.ClassLoaders$AppClassLoader@3d2ee678}
```
with the stack trace:
```bash
at software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler.onHeaders(AsyncAfterTransmissionInterceptorCallingResponseHandler.java:67)
at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$WrappedErrorForwardingResponseHandler.onHeaders(MakeAsyncHttpRequestStage.java:148)
at com.github.matsluni.akkahttpspi.RequestRunner.$anonfun$run$1(RequestRunner.scala:41)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

I see that the build of dd-trace-java is looking for `JAVA_11_HOME` by default so my questions are, 
1.  What are the supported JDKs for `dd-trace-java`?
2. Could this exception cause traces to be dropped/missed/unreported?

**Comment by bm1549** [comment]
@gbiv thanks for reporting this. If this is still an issue, please open up a support ticket at https://www.datadoghq.com/support/
