### ISSUE TITLE
Issue starting datadog java agent 

### ISSUE THREAD

**Issue by connorwescott42** [DataDog/dd-trace-java#342]
Hello,

I am getting an exception when starting the agent on my system. I am able to start my program directly without the agent and no exceptions are thrown.

java -javaagent:dd-java-agent-0.9.0.jar -jar head-app.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.IllegalArgumentException
        at sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
        at sun.instrument.InstrumentationImpl.appendToBootstrapClassLoaderSearch(Unknown Source)
        at datadog.trace.agent.TracingAgent.startAgent(TracingAgent.java:55)
        at datadog.trace.agent.TracingAgent.premain(TracingAgent.java:32)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed

I have also supplied my java version:

java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

I have also tried version 0.6.0 of the agent, but I am receiving the same error.

Thanks!

**Comment by tylerbenson** [comment]
@connorwescott42 At that point in the code, the agent tried to write out some jars to be loaded onto the classpath.  This might be caused by the agent being unable to write those to the file system.  Can you try launching your application in a debugger (attaching to it via remote debugging won't work) and seeing if those files were successfully written to the file system?

Thanks!

**Comment by connorwescott42** [comment]
@tylerbenson Thanks for your assistance. After placing a breakpoint on the failing line, I noticed that the jars were being stored in "C:\\Windows\\Temp", which is a secure directory. I simply changed my System Environment variable to set TMP and TEMP to a more appropriate value ("%USERPROFILE%\AppData\Local\Temp") and it is working now!

Thanks again.
