### ISSUE TITLE
AppSec: Logs full of warnings "java.lang.IllegalStateException: Raw URI set already"

### ISSUE THREAD

**Issue by jokalli2** [DataDog/dd-trace-java#3484]
Hi,

We have enabled the AppSec functionality. It seems to be working fine, but our service logs are full of warnings. We are using the latest dd-trace-java version and the service is Play Framework 2.8.

The logged error:

[dd.trace 2022-04-08 10:23:53:026 +0300] [application-akka.actor.default-dispatcher-263] WARN datadog.trace.api.gateway.InstrumentationGateway - Callback for EventType{name='server.request.method.uri.raw'} threw.
--
java.lang.IllegalStateException: Raw URI set already
at com.datadog.appsec.gateway.AppSecRequestContext.setRawURI(AppSecRequestContext.java:172)
at com.datadog.appsec.gateway.GatewayBridge$MethodAndRawURICallback.apply(GatewayBridge.java:376)
at com.datadog.appsec.gateway.GatewayBridge$MethodAndRawURICallback.apply(GatewayBridge.java:361)
at datadog.trace.api.gateway.InstrumentationGateway$6.apply(InstrumentationGateway.java:151)
at datadog.trace.api.gateway.InstrumentationGateway$6.apply(InstrumentationGateway.java:145)
at datadog.trace.bootstrap.instrumentation.decorator.HttpServerDecorator.callIGCallbackURI(HttpServerDecorator.java:299)
at datadog.trace.bootstrap.instrumentation.decorator.HttpServerDecorator.onRequest(HttpServerDecorator.java:153)
at datadog.trace.instrumentation.play26.PlayHttpServerDecorator.onRequest(PlayHttpServerDecorator.java:113)
at play.api.mvc.ActionBuilder$anon$9.apply(Action.scala:384)
at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
at scala.util.Try$.apply(Try.scala:210)
at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:417)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by ValentinZakharov** [comment]
Thanks for the report @jokalli2. We're still working on full support Play Framework in the AppSec. Please, let me take a look closer on Play 2.8

**Comment by ValentinZakharov** [comment]
Hello @jokalli2. I'd like to let you know, we just released new version of Java tracer (`0.100.0`) with fix for the Play framework 2.8 issue.
Please, let us know, if this works for you.

**Comment by jokalli2** [comment]
Hello @ValentinZakharov . Looks like this problem is fixed. I'll close the issue. Thanks a lot!
