### ISSUE TITLE
AppSec could not start because of an unexpected error

### ISSUE THREAD

**Issue by billgowendavis** [DataDog/dd-trace-java#3575]
Recently tried enabling AppSec for a Java app but encountered the following error when attempting it: 
```log
[dd.trace 2022-05-27 04:03:00:928 +0000] [main] CRITICAL com.datadog.appsec.AppSecSystem - AppSec could not start because of an unexpected error. No security activities will be collected. Please contact support at https://docs.datadoghq.com/help/ for help.
java.lang.UnsatisfiedLinkError: /tmp/pwaf5801679322118403215/libsqreen_jni.so: /tmp/pwaf5801679322118403215/libsqreen_jni.so: failed to map segment from shared object
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at io.sqreen.powerwaf.NativeLibLoader.load(NativeLibLoader.java:30)
        at io.sqreen.powerwaf.Powerwaf.initialize(Powerwaf.java:56)
        at com.datadog.appsec.powerwaf.LibSqreenInitialization.initPowerWAF(LibSqreenInitialization.java:17)
        at com.datadog.appsec.powerwaf.LibSqreenInitialization.<clinit>(LibSqreenInitialization.java:12)
        at com.datadog.appsec.powerwaf.PowerWAFModule.applyConfig(PowerWAFModule.java:149)
        at com.datadog.appsec.powerwaf.PowerWAFModule.config(PowerWAFModule.java:130)
        at com.datadog.appsec.AppSecSystem.loadModules(AppSecSystem.java:112)
        at com.datadog.appsec.AppSecSystem.doStart(AppSecSystem.java:72)
        at com.datadog.appsec.AppSecSystem.start(AppSecSystem.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at datadog.trace.bootstrap.Agent.startAppSec(Agent.java:577)
        at datadog.trace.bootstrap.Agent.maybeStartAppSec(Agent.java:568)
        at datadog.trace.bootstrap.Agent.access$500(Agent.java:46)
        at datadog.trace.bootstrap.Agent$InstallDatadogTracerCallback.execute(Agent.java:377)
        at datadog.trace.bootstrap.Agent.start(Agent.java:244)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:60)
        at datadog.trace.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[dd.trace 2022-05-27 04:03:00:940 +0000] [main] WARN datadog.trace.bootstrap.Agent - Not starting AppSec subsystem: null
[dd.trace 2022-05-27 04:03:01:240 +0000] [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.101.0~631dd35132","os_name":"Linux","os_version":"4.14.276-211.499.amzn2.x86_64","architecture":"amd64","lang":"jvm","lang_version":"11.0.15","jvm_vendor":"Amazon.com Inc.","jvm_version":"11.0.15+9-LTS","java_class_version":"55.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"gluon-core","agent_url":"http://localhost:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":true,"appsec_enabled":true,"dd_version":"0.97.0~a0891025ac","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"90adfb69-b751-4b56-bc72-eda5515b5dc6","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false},"cws_enabled":false,"cws_tls_refresh":5000}
```

**Comment by bm1549** [comment]
@billgowendavis if this is still an issue, please open up a support ticket at https://www.datadoghq.com/support/
