### ISSUE TITLE
ClassCast Exception when datadog instrumentation and Kamon instrumentation both are enabled

### ISSUE THREAD

**Issue by nmadhavi33** [DataDog/dd-trace-java#3581]
I am seeing below ClassCastException when Kamon and datadog instrumentation enabled for akka framework application

ERROR 2022-06-02 16:37:49  Logger : An error occurred while trying to apply an advisor: java.lang.ClassCastException: akka.actor.ActorCell cannot be cast to kamon.instrumentation.akka.instrumentations.HasActorMonitor
        at kamon.instrumentation.akka.instrumentations.HasActorMonitor$.actorMonitor(ActorInstrumentation.scala:95)
        at kamon.instrumentation.akka.instrumentations.SendMessageAdvice$.onEnter(ActorInstrumentation.scala:136)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)
        at akka.actor.Cell.sendMessage(ActorCell.scala:327)
        at akka.actor.Cell.sendMessage$(ActorCell.scala:326)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)
        at akka.actor.LocalActorRef.$bang(ActorRef.scala:448)
        at akka.cluster.client.ClusterClient.<init>(ClusterClient.scala:403)
        at akka.cluster.client.ClusterClient$.$anonfun$props$1(ClusterClient.scala:296)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
        at akka.actor.Props.newActor(Props.scala:226)
        at akka.actor.ActorCell.newActor(ActorCell.scala:616)
        at akka.actor.ActorCell.create(ActorCell.scala:643)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:514)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:536)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
        at akka.dispatch.Mailbox.run(Mailbox.scala:230)
        at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:662)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

**Comment by pete-proton** [comment]
experiencing the same issue. does it impact functionality?
