### ISSUE TITLE
Disable "statement update" for RemoteJDBCInstrumentationTest

### ISSUE THREAD

**Issue by nayeem-kamal** [DataDog/dd-trace-java#3885]
This test fails sometimes with Too many invocations

https://output.circle-artifacts.com/output/job/3ed71dd1-874b-4fef-9e8d-c60a4aa802c2/artifacts/0/reports/dd-java-agent/instrumentation/jdbc/tests/oldH2Test/classes/RemoteJDBCInstrumentationTest.html

```
Too many invocations for:

0 * _   (1 invocation)

Matching invocations (ordered by last occurrence):

1 * $spock_sharedField_STATS_D_CLIENT.count('trace.pending.created', 40, [])   <-- this triggered the error


	at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:70)
	at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:50)
	at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:51)
	at org.spockframework.mock.runtime.MockController.handle(MockController.java:40)
	at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:72)
	at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
	at datadog.trace.core.monitor.HealthMetrics$Flush.reportIfChanged(HealthMetrics.java:283)
	at datadog.trace.core.monitor.HealthMetrics$Flush.run(HealthMetrics.java:268)
	at datadog.trace.core.monitor.HealthMetrics$Flush.run(HealthMetrics.java:231)
	at datadog.trace.util.AgentTaskScheduler$PeriodicTask.run(AgentTaskScheduler.java:299)
	at datadog.trace.util.AgentTaskScheduler$Worker.run(AgentTaskScheduler.java:254)
	at java.lang.Thread.run(Thread.java:830)
```

**Comment by nayeem-kamal** [comment]
The assertion causing the error has been removed.
