### ISSUE TITLE
Failed to determine dependency

### ISSUE THREAD

**Issue by parasappafluke** [DataDog/dd-trace-java#4242]
Hi,
The tracer agent throwing below warning in the console for our one of spring-boot application, however we observed that the service is appearing in the Datadg->APM section. Does this error means will miss some of the telemetry data to appear in DD or is it ignorable?
`[dd.trace 2022-11-11 10:03:02:622 +0000] [dd-task-scheduler] INFO datadog.communication.monitor.DDAgentStatsDConnection - Detected /var/run/datadog/dsd.socket.  Using it to send StatsD data.80`

`[dd.trace 2022-11-11 10:03:15:895 +0000] [dd-task-scheduler] WARN datadog.telemetry.dependency.DependencyResolver - Failed to determine dependency for uri jar:file:/adp-pt-data-parser.jar!/BOOT-INF/lib/jakarta.inject-2.6.1.jar!/79java.lang.NullPointerException: Expected arg to be non-null78    at datadog.telemetry.dependency.Dependency.checkNotNull(Dependency.java:65)77    at datadog.telemetry.dependency.Dependency.<init>(Dependency.java:57)`

Thanks 
Parasappa

**Comment by smola** [comment]
@parasappafluke Your service will still appear in the UI. As of today, these dependencies are not used in generally available features. So you can ignore this warning for now. We are now investigating the issue.

**Comment by parasappafluke** [comment]
@smola Thank you for the quick response. Let us know once it is fixed.

**Comment by parasappafluke** [comment]
@smola  Thank you
