### ISSUE TITLE
Datadog trace java BufferOverflowException

### ISSUE THREAD

**Issue by skimwpi** [DataDog/dd-trace-java#4430]
Hi, after upgrading from dd-trace-java 0.115.0 to 1.2, I'm occasionally getting the following in my logs

`[dd.trace 2022-12-14 20:53:50:699 +0000] [dd-trace-monitor] ERROR datadog.trace.agent.core.DDSpan -
java.nio.BufferOverflowException
        at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:666)
        at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:200)
        at com.datadog.profiling.context.LEB128Support.putVarint(LEB128Support.java:51)
        at com.datadog.profiling.context.IntervalEncoder.finish(IntervalEncoder.java:327)
        at com.datadog.profiling.context.PerSpanTracingContextTracker.encodeIntervals(PerSpanTracingContextTracker.java:463)
        at com.datadog.profiling.context.PerSpanTracingContextTracker.persist(PerSpanTracingContextTracker.java:294)
        at datadog.trace.agent.core.DDSpan.storeContextToTag(DDSpan.java:265)
        at datadog.trace.agent.core.CoreTracer.write(CoreTracer.java:836)
        at datadog.trace.agent.core.PendingTrace.write(PendingTrace.java:274)
        at datadog.trace.agent.core.PendingTrace.write(PendingTrace.java:242)
        at datadog.trace.agent.core.PendingTraceBuffer$DelayingPendingTraceBuffer$Worker.run(PendingTraceBuffer.java:167)
        at java.base/java.lang.Thread.run(Thread.java:829)`

I do NOT have DD_TRACE_DEBUG set, and DD_PROFILING_ENABLED is enabled. I'm using Java 11.
Is there a way to increase the buffer or is this a bug? I'm not sure how to address this issue.

**Comment by skimwpi** [comment]
For additional clarification, I'm running in Alpine 3.14

**Comment by richardstartin** [comment]
Hi @skimwpi this error is benign but is part of a profiling feature we are replacing. If you upgrade to 1.3.0 and are running a JDK version JDK8 8u352+, JDK11 11.0.17+, JDK17 17.0.5+ or latest non LTS this code should not execute and we will use a different mechanism to correlate your traces with profiles.

**Comment by skimwpi** [comment]
Thank you. I appreciate for following up and will upgrade to 1.3

**Comment by richardstartin** [comment]
This feature was removed in v1.6.0
