### ISSUE TITLE
NPE when tracing Kafka messages 

### ISSUE THREAD

**Issue by Manan-Kothari** [DataDog/dd-trace-java#4762]
This is happening with the latest version of the agent as we always grab the latest on our builds (eventually moving away from this and will use the admission controller to inject the library) 

It looks like this preventing us from producing some messages. 

```
java.lang.NullPointerException: null
	at datadog.trace.instrumentation.kafka_clients.KafkaProducerCallback.onCompletion(KafkaProducerCallback.java:33) ~[?:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:959) ~[kafka-clients-2.5.1.jar!/:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:862) ~[kafka-clients-2.5.1.jar!/:?]
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:863) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at brave.kafka.clients.TracingProducer.send(TracingProducer.java:129) ~[brave-instrumentation-kafka-clients-5.12.7.jar!/:?]
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:562) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:369) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at p44.shipment.tracking.service.kafka.ClientPushMessageProducer.sendMessage(ClientPushMessageProducer.java:26) ~[classes!/:?]
	at p44.shipment.tracking.service.ClientPushService.lambda$sendPushUpdate$0(ClientPushService.java:102) ~[classes!/:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at p44.shipment.tracking.service.ClientPushService.sendPushUpdate(ClientPushService.java:102) ~[classes!/:?]
	at p44.shipment.tracking.service.ShipmentPublisherService.publishIfNecessary(ShipmentPublisherService.java:80) ~[classes!/:?]
	at p44.shipment.tracking.service.ShipmentUpdateService.publishShipment(ShipmentUpdateService.java:229) ~[classes!/:?]
	at p44.shipment.tracking.service.ShipmentUpdateService.mergeUpsertAndPublishShipment(ShipmentUpdateService.java:172) ~[classes!/:?]
	at p44.shipment.tracking.service.ShipmentUpdateService.findMigrateMergeAndPublishShipmentPartials(ShipmentUpdateService.java:88) ~[classes!/:?]
	at p44.shipment.tracking.service.kafka.PartialShipmentUpdateInformConsumer.onPartialShipmentUpdateInform(PartialShipmentUpdateInformConsumer.java:39) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor492.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:329) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:87) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:52) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter$$FastClassBySpringCGLIB$$cde8c01d.invoke(<generated>) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.cloud.sleuth.instrument.messaging.MessageListenerMethodInterceptor.invoke(TraceMessagingAutoConfiguration.java:394) ~[spring-cloud-sleuth-core-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter$$EnhancerBySpringCGLIB$$6736c0b0.onMessage(<generated>) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2044) ~[spring-kafka-2.5.14.RELEASE.jar!/:2.5.14.RELEASE]
```

For now we are downgrading by setting the library version to 1.60 

```
RUN wget -O /dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'  
->
RUN wget -O /dd-java-agent.jar https://dtdg.co/java-tracer-v1.6.0
```

**Comment by mcculls** [comment]
Hi @Manan-Kothari, this is a known issue which will be fixed soon in a patch release - I'll update this ticket when it's available for download

**Comment by mcculls** [comment]
Hi @Manan-Kothari version 1.8.3 of the Java Tracer has just been released with a fix for this NPE

**Comment by Manan-Kothari** [comment]
Cool, thanks for the update and quick fix.
