### ISSUE TITLE
FelixSmokeTest fails with NPE and bytebuddy exception

### ISSUE THREAD

**Issue by smola** [DataDog/dd-trace-java#4826]
Example job: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/22255/workflows/dbb52cd0-30d5-4334-a419-605674e889d6/jobs/614701/tests

```
Condition not satisfied:

!logHasErrors
||
|true
false

	at datadog.smoketest.AbstractOSGiSmokeTest.example application runs without errors(AbstractOSGiSmokeTest.groovy:60)
```

In the reports, I can see the following error:

```
[dd.trace 2023-03-02 12:00:30:735 +0000] [pool-2-thread-1] DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for org.apache.felix.framework.BundleWiringImpl$BundleClassLoader
java.lang.NullPointerException
        at datadog.trace.instrumentation.osgi43.BundleWiringHelper.searchDirectWires(BundleWiringHelper.java:90)
        at datadog.trace.instrumentation.osgi43.BundleWiringHelper.loadClass(BundleWiringHelper.java:68)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1981)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory.loadType(TypeFactory.java:274)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory.lookupType(TypeFactory.java:255)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory.resolveType(TypeFactory.java:220)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.doResolve(TypeFactory.java:380)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.outline(TypeFactory.java:366)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.getModifiers(TypeFactory.java:338)
        at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
        at net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
        at net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7980)
        at net.bytebuddy.matcher.VisibilityMatcher.doMatch(VisibilityMatcher.java:48)
        at net.bytebuddy.matcher.VisibilityMatcher.doMatch(VisibilityMatcher.java:27)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:47)
        at net.bytebuddy.matcher.ErasureMatcher.doMatch(ErasureMatcher.java:50)
        at net.bytebuddy.matcher.ErasureMatcher.doMatch(ErasureMatcher.java:29)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.MethodParameterTypeMatcher.doMatch(MethodParameterTypeMatcher.java:48)
        at net.bytebuddy.matcher.MethodParameterTypeMatcher.doMatch(MethodParameterTypeMatcher.java:27)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.CollectionItemMatcher.doMatch(CollectionItemMatcher.java:48)
        at net.bytebuddy.matcher.CollectionItemMatcher.doMatch(CollectionItemMatcher.java:26)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:47)
        at net.bytebuddy.matcher.MethodParametersMatcher.doMatch(MethodParametersMatcher.java:49)
        at net.bytebuddy.matcher.MethodParametersMatcher.doMatch(MethodParametersMatcher.java:28)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:146)
        at net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:506)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.toTypeWriter(RedefinitionDynamicTypeBuilder.java:203)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4057)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:12106)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12041)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1800(AgentBuilder.java:11758)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12521)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12453)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11984)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at datadog.trace.agent.tooling.bytebuddy.DDJava9ClassFileTransformer.transform(DDJava9ClassFileTransformer.java:60)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2312)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2130)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2064)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1533)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at datadog.smoketest.osgi.subscribing.AsyncSubscriber.doReceive(AsyncSubscriber.java:18)
        at datadog.smoketest.osgi.messaging.SubscriberSupport.receive(SubscriberSupport.java:8)
        at datadog.smoketest.osgi.publishing.AsyncPublisher$PublishTask.run(AsyncPublisher.java:39)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

and

```
[dd.trace 2023-03-02 12:00:30:736 +0000] [pool-2-thread-1] DEBUG datadog.trace.agent.tooling.AgentInstaller$TransformLoggingListener - Transformation failed - instrumentation.target.class=datadog.smoketest.osgi.subscribing.AsyncSubscriber$ReceiveTask instrumentation.target.classloader=osgi-subscribing [5]
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for datadog.smoketest.osgi.messaging.Message
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.doResolve(TypeFactory.java:383)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.outline(TypeFactory.java:366)
        at datadog.trace.agent.tooling.bytebuddy.outline.TypeFactory$LazyType.getModifiers(TypeFactory.java:338)
        at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
        at net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
        at net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7980)
        at net.bytebuddy.matcher.VisibilityMatcher.doMatch(VisibilityMatcher.java:48)
        at net.bytebuddy.matcher.VisibilityMatcher.doMatch(VisibilityMatcher.java:27)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:47)
        at net.bytebuddy.matcher.ErasureMatcher.doMatch(ErasureMatcher.java:50)
        at net.bytebuddy.matcher.ErasureMatcher.doMatch(ErasureMatcher.java:29)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.MethodParameterTypeMatcher.doMatch(MethodParameterTypeMatcher.java:48)
        at net.bytebuddy.matcher.MethodParameterTypeMatcher.doMatch(MethodParameterTypeMatcher.java:27)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.CollectionItemMatcher.doMatch(CollectionItemMatcher.java:48)
        at net.bytebuddy.matcher.CollectionItemMatcher.doMatch(CollectionItemMatcher.java:26)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:47)
        at net.bytebuddy.matcher.MethodParametersMatcher.doMatch(MethodParametersMatcher.java:49)
        at net.bytebuddy.matcher.MethodParametersMatcher.doMatch(MethodParametersMatcher.java:28)
        at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
        at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:146)
        at net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:506)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.toTypeWriter(RedefinitionDynamicTypeBuilder.java:203)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4057)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:12106)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12041)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1800(AgentBuilder.java:11758)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12521)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12453)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11984)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at datadog.trace.agent.tooling.bytebuddy.DDJava9ClassFileTransformer.transform(DDJava9ClassFileTransformer.java:60)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2312)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2130)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2064)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1533)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
        at datadog.smoketest.osgi.subscribing.AsyncSubscriber.doReceive(AsyncSubscriber.java:18)
        at datadog.smoketest.osgi.messaging.SubscriberSupport.receive(SubscriberSupport.java:8)
        at datadog.smoketest.osgi.publishing.AsyncPublisher$PublishTask.run(AsyncPublisher.java:39)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mcculls** [comment]
Looks like a race condition where the tracer was introspecting a bundle's wiring and one of those wires got invalidated. Probably due to a bundle being uninstalled as part of shutting down the test while the test's async publishing was still in-progress. Should be straightforward to fix the test, but also make the introspection code a bit more robust.

**Comment by mcculls** [comment]
Closing as fixed
