### ISSUE TITLE
io.sqreen.powerwaf.exception.UnsupportedVMException: Unsupported OS: Linux

### ISSUE THREAD

**Issue by dmitry-cherkas** [DataDog/dd-trace-java#4833]
We are facing the below error when running java DataDog agent `1.6.0~c256ff8259` with a docker image based on `rockylinux:9.1.20221221` with the `-Ddd.appsec.enabled=true` parameter. Would appreciate if we could get some advise on the resolution.

```
[dd.trace 2023-03-02 16:01:45:937 +0000] [main] INFO io.sqreen.powerwaf.NativeLibLoader - Will load native library
[dd.trace 2023-03-02 16:01:45:985 +0000] [main] WARN com.datadog.appsec.powerwaf.LibSqreenInitialization - Error initializing WAF library
io.sqreen.powerwaf.exception.UnsupportedVMException: Unsupported OS: Linux
    at io.sqreen.powerwaf.NativeLibLoader.getOsType(NativeLibLoader.java:133)
    at io.sqreen.powerwaf.NativeLibLoader.extractLib(NativeLibLoader.java:35)
    at io.sqreen.powerwaf.NativeLibLoader.load(NativeLibLoader.java:28)
    at io.sqreen.powerwaf.Powerwaf.initialize(Powerwaf.java:59)
    at com.datadog.appsec.powerwaf.LibSqreenInitialization.initPowerWAF(LibSqreenInitialization.java:17)
    at com.datadog.appsec.powerwaf.LibSqreenInitialization.<clinit>(LibSqreenInitialization.java:12)
    at com.datadog.appsec.powerwaf.PowerWAFModule.applyConfig(PowerWAFModule.java:218)
    at com.datadog.appsec.powerwaf.PowerWAFModule.config(PowerWAFModule.java:167)
    at com.datadog.appsec.AppSecSystem.loadModules(AppSecSystem.java:135)
    at com.datadog.appsec.AppSecSystem.doStart(AppSecSystem.java:81)
    at com.datadog.appsec.AppSecSystem.start(AppSecSystem.java:41)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at datadog.trace.bootstrap.Agent.startAppSec(Agent.java:641)
    at datadog.trace.bootstrap.Agent.maybeStartAppSec(Agent.java:627)
    at datadog.trace.bootstrap.Agent.access$500(Agent.java:51)
    at datadog.trace.bootstrap.Agent$InstallDatadogTracerCallback.execute(Agent.java:400)
    at datadog.trace.bootstrap.Agent.start(Agent.java:258)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:72)
    at datadog.trace.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:54)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
[dd.trace 2023-03-02 16:01:45:992 +0000] [main] CRITICAL com.datadog.appsec.powerwaf.LibSqreenInitialization - AppSec could not load libddwaf native library, as a result, AppSec could not start. No securit
[dd.trace 2023-03-02 16:01:45:993 +0000] [main] ERROR com.datadog.appsec.AppSecSystem - Startup of appsec module powerwaf failed
com.datadog.appsec.AppSecModule$AppSecModuleActivationException: In-app WAF initialization failed. See previous log entries
    at com.datadog.appsec.powerwaf.PowerWAFModule.applyConfig(PowerWAFModule.java:219)
    at com.datadog.appsec.powerwaf.PowerWAFModule.config(PowerWAFModule.java:167)
    at com.datadog.appsec.AppSecSystem.loadModules(AppSecSystem.java:135)
    at com.datadog.appsec.AppSecSystem.doStart(AppSecSystem.java:81)
    at com.datadog.appsec.AppSecSystem.start(AppSecSystem.java:41)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at datadog.trace.bootstrap.Agent.startAppSec(Agent.java:641)
    at datadog.trace.bootstrap.Agent.maybeStartAppSec(Agent.java:627)
    at datadog.trace.bootstrap.Agent.access$500(Agent.java:51)
    at datadog.trace.bootstrap.Agent$InstallDatadogTracerCallback.execute(Agent.java:400)
    at datadog.trace.bootstrap.Agent.start(Agent.java:258)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:72)
    at datadog.trace.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:54)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
[dd.trace 2023-03-02 16:01:46:007 +0000] [main] INFO com.datadog.appsec.AppSecSystem - AppSec is FULLY_ENABLED with
[dd.trace 2023-03-02 16:01:46:324 +0000] [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"1.6.0~c256ff8259","os_name":"Linux","os_version":"5.4.209-

```

**Comment by smola** [comment]
@dmitry-cherkas Thank you for reporting this. We'll investigate the issue.

**Comment by smola** [comment]
We identified the root cause (not detecting glibc vs musl properly on Rocky Linux) and will work on a fix for an upcoming release.

**Comment by dmitry-cherkas** [comment]
@smola, that's great news, thanks for the update!

**Comment by fcarrero** [comment]
umm issue is still present using the latest versions 1.1.8.2 over a docker imagen https://hub.docker.com/layers/library/maven/3.6.2-jdk-8/images/sha256-cb4a1ef604b30a109bd061ca0e3410e7b335e6ede740d530df06c9b31cdd7bbb?context=explore

with the same error

´io.sqreen.powerwaf.exception.TimeoutPowerwafException: Timeout´
