### ISSUE TITLE
ci-visibility test are flaky with IBM JDK

### ISSUE THREAD

**Issue by PerfectSlayer** [DataDog/dd-trace-java#5618]
Here is the kind of error the CI raises:
```
> Task :dd-java-agent:agent-ci-visibility:test
Pointer: 000000007FFFFFFF has is not object aligned (to 8 bytes) 
07:04:24.585 0x15bd00    j9mm.141    *   ** ASSERTION FAILED ** at ./MarkingScheme.hpp:70: ((false))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2023/07/21 07:04:24 - please wait.
JVMDUMP032I JVM requested System dump using '/tmp/core.20230721.070424.748.0001.dmp' in response to an event

ChannelContextTest > randomized test: buffer capacity #bufferCapacity > randomized test: buffer capacity 8 FAILED
    java.lang.AbstractMethodError at ChannelContextTest.groovy:239

ChannelContextTest > randomized test: buffer capacity #bufferCapacity > randomized test: buffer capacity 9 FAILED
    java.lang.AbstractMethodError at ChannelContextTest.groovy:239

ChannelContextTest > randomized test: buffer capacity #bufferCapacity > randomized test: buffer capacity 10 FAILED
    java.lang.AbstractMethodError at ChannelContextTest.groovy:239
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.1307.  Review the manual for the external program to find where the core dump is written and ensure the program does not truncate it.

> Task :internal-api:forkedTest
> Task :dd-trace-ot:forkedTest

> Task :dd-java-agent:agent-ci-visibility:test
JVMPORT049I The core file created by child process with pid = 1307 was not found. Review the documentation for the /proc/sys/kernel/core_pattern program "|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" to find where the core file is written and ensure that program does not truncate it.

JVMDUMP012E Error in System dump: /tmp/core.20230721.070424.748.0001.dmp
JVMDUMP032I JVM requested Java dump using '/tmp/javacore.20230721.070424.748.0002.txt' in response to an event
JVMDUMP010I Java dump written to /tmp/javacore.20230721.070424.748.0002.txt
JVMDUMP032I JVM requested Snap dump using '/tmp/Snap.20230721.070424.748.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /tmp/Snap.20230721.070424.748.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".

519 tests completed, 3 failed, 1 skipped
```

Here is the strace trace:
```
3XMTHREADINFO      "Test worker" J9VMThread:0x0000000000016800, omrthread_t:0x00007F3E48007960, java/lang/Thread:0x00000000D00FE6E8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x00000000D00DB650)
3XMTHREADINFO1            (native thread ID:0x2F0, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x00007F3E50000000, to:0x00007F3E50800000, size:0x800000)
3XMCPUTIME               CPU usage total: 8.002264229 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at datadog/trace/civisibility/ipc/ChannelContextTest$InMemoryReadableByteChannel.write(ChannelContextTest.groovy:390)
4XESTACKTRACE                at datadog/trace/civisibility/ipc/ChannelContext.writeResponse(ChannelContext.java:75(Compiled Code))
4XESTACKTRACE                at datadog/trace/civisibility/ipc/ChannelContext.processBuffer(ChannelContext.java:58(Compiled Code))
4XESTACKTRACE                at datadog/trace/civisibility/ipc/ChannelContext.read(ChannelContext.java:29(Compiled Code))
4XESTACKTRACE                at sun/reflect/GeneratedMethodAccessor105.invoke(Bytecode PC:40)
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:209(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/PojoMetaMethodSite.call(PojoMetaMethodSite.java:51(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/AbstractCallSite.call(AbstractCallSite.java:139(Compiled Code))
4XESTACKTRACE                at datadog/trace/civisibility/ipc/ChannelContextTest.$spock_feature_0_9(ChannelContextTest.groovy:239(Compiled Code))
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90(Compiled Code))
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
4XESTACKTRACE                at org/spockframework/util/ReflectionUtil.invokeMethod(ReflectionUtil.java:198(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo.lambda$new$0(MethodInfo.java:47)
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo$$Lambda$150/0x000000004903d2e0.invoke(Bytecode PC:6)
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo.invoke(MethodInfo.java:148(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/extension/MethodInvocation.proceed(MethodInvocation.java:102(Compiled Code))
4XESTACKTRACE                at org/spockframework/junit4/ExceptionAdapterInterceptor.intercept(ExceptionAdapterInterceptor.java:13(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/extension/MethodInvocation.proceed(MethodInvocation.java:101(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invoke(PlatformSpecRunner.java:398(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.runFeatureMethod(PlatformSpecRunner.java:324(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/IterationNode.execute(IterationNode.java:48(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/IterationNode.execute(IterationNode.java:11(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$273/0x000000004996c120.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$272/0x000000004996bc90.invoke(Bytecode PC:5(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/SpockNode.sneakyInvoke(SpockNode.java:40(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/IterationNode.lambda$around$0(IterationNode.java:63)
4XESTACKTRACE                at org/spockframework/runtime/IterationNode$$Lambda$308/0x0000000049a0c930.run(Bytecode PC:12)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.lambda$createMethodInfoForDoRunIteration$5(PlatformSpecRunner.java:236)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner$$Lambda$309/0x0000000048ced220.invoke(Bytecode PC:6)
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo.invoke(MethodInfo.java:148(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/extension/MethodInvocation.proceed(MethodInvocation.java:102(Compiled Code))
4XESTACKTRACE                at org/spockframework/junit4/ExceptionAdapterInterceptor.intercept(ExceptionAdapterInterceptor.java:13(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/extension/MethodInvocation.proceed(MethodInvocation.java:101(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invoke(PlatformSpecRunner.java:398(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.runIteration(PlatformSpecRunner.java:218(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/IterationNode.around(IterationNode.java:63)
4XESTACKTRACE                at org/spockframework/runtime/IterationNode.around(IterationNode.java:11)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$271/0x000000004996b830.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.executeRecursively(NodeTestTask.java:138(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.execute(NodeTestTask.java:95(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
4XESTACKTRACE                at org/spockframework/runtime/ParameterizedFeatureChildExecutor.execute(ParameterizedFeatureChildExecutor.java:53)
4XESTACKTRACE                at org/spockframework/runtime/PlatformParameterizedSpecRunner.runIterations(PlatformParameterizedSpecRunner.java:187(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformParameterizedSpecRunner.runParameterizedFeature(PlatformParameterizedSpecRunner.java:45)
4XESTACKTRACE                at org/spockframework/runtime/ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:40)
4XESTACKTRACE                at org/spockframework/runtime/ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:16)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$273/0x000000004996c120.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$272/0x000000004996bc90.invoke(Bytecode PC:5(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/SpockNode.sneakyInvoke(SpockNode.java:40(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/FeatureNode.lambda$around$0(FeatureNode.java:29)
4XESTACKTRACE                at org/spockframework/runtime/FeatureNode$$Lambda$294/0x0000000049995390.run(Bytecode PC:12)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:199)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner$$Lambda$295/0x0000000049994650.invoke(Bytecode PC:6)
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo.invoke(MethodInfo.java:148(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invoke(PlatformSpecRunner.java:390(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.runFeature(PlatformSpecRunner.java:192)
4XESTACKTRACE                at org/spockframework/runtime/FeatureNode.around(FeatureNode.java:29)
4XESTACKTRACE                at org/spockframework/runtime/FeatureNode.around(FeatureNode.java:8)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$271/0x000000004996b830.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.executeRecursively(NodeTestTask.java:138(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.execute(NodeTestTask.java:95(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService$$Lambda$277/0x000000004996d2a0.accept(Bytecode PC:6)
4XESTACKTRACE                at java/util/ArrayList.forEach(ArrayList.java:1270(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$273/0x000000004996c120.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$272/0x000000004996bc90.invoke(Bytecode PC:5(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/SpockNode.sneakyInvoke(SpockNode.java:40(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/SpecNode.lambda$around$0(SpecNode.java:63)
4XESTACKTRACE                at org/spockframework/runtime/SpecNode$$Lambda$290/0x0000000049993520.run(Bytecode PC:12)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:61)
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner$$Lambda$291/0x0000000049993050.invoke(Bytecode PC:6)
4XESTACKTRACE                at org/spockframework/runtime/model/MethodInfo.invoke(MethodInfo.java:148(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:407(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.invoke(PlatformSpecRunner.java:390(Compiled Code))
4XESTACKTRACE                at org/spockframework/runtime/PlatformSpecRunner.runSpec(PlatformSpecRunner.java:55)
4XESTACKTRACE                at org/spockframework/runtime/SpecNode.around(SpecNode.java:63)
4XESTACKTRACE                at org/spockframework/runtime/SpecNode.around(SpecNode.java:11)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$271/0x000000004996b830.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.executeRecursively(NodeTestTask.java:138(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.execute(NodeTestTask.java:95(Compiled Code))
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService$$Lambda$277/0x000000004996d2a0.accept(Bytecode PC:6)
4XESTACKTRACE                at java/util/ArrayList.forEach(ArrayList.java:1270)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$273/0x000000004996c120.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$272/0x000000004996bc90.invoke(Bytecode PC:5)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/Node.around(Node.java:137)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask$$Lambda$271/0x000000004996b830.execute(Bytecode PC:4)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/ThrowableCollector.execute(ThrowableCollector.java:73)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.executeRecursively(NodeTestTask.java:138)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/NodeTestTask.execute(NodeTestTask.java:95)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
4XESTACKTRACE                at org/junit/platform/engine/support/hierarchical/HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator$$Lambda$234/0x000000004995ba40.accept(Bytecode PC:12)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
4XESTACKTRACE                at org/junit/platform/launcher/core/EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
4XESTACKTRACE                at org/junit/platform/launcher/core/DefaultLauncher.execute(DefaultLauncher.java:114)
4XESTACKTRACE                at org/junit/platform/launcher/core/DefaultLauncher.execute(DefaultLauncher.java:86)
4XESTACKTRACE                at org/junit/platform/launcher/core/DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:508)
4XESTACKTRACE                at org/gradle/internal/dispatch/ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
4XESTACKTRACE                at org/gradle/internal/dispatch/ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
4XESTACKTRACE                at org/gradle/internal/dispatch/ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
4XESTACKTRACE                at org/gradle/internal/dispatch/ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
4XESTACKTRACE                at com/sun/proxy/$Proxy2.stop(Bytecode PC:11)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/worker/TestWorker$3.run(TestWorker.java:193)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/worker/TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/worker/TestWorker.execute(TestWorker.java:100)
4XESTACKTRACE                at org/gradle/api/internal/tasks/testing/worker/TestWorker.execute(TestWorker.java:60)
4XESTACKTRACE                at org/gradle/process/internal/worker/child/ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
4XESTACKTRACE                at org/gradle/process/internal/worker/child/SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
4XESTACKTRACE                at org/gradle/process/internal/worker/child/SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
4XESTACKTRACE                at worker/org/gradle/process/internal/worker/GradleWorkerMain.run(GradleWorkerMain.java:69)
4XESTACKTRACE                at worker/org/gradle/process/internal/worker/GradleWorkerMain.main(GradleWorkerMain.java:74)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK                (0x00007F3E4E85CE22 [libj9prt29.so+0x5ce22])
4XENATIVESTACK                (0x00007F3E4E827A33 [libj9prt29.so+0x27a33])
4XENATIVESTACK                (0x00007F3E4E85D31A [libj9prt29.so+0x5d31a])
4XENATIVESTACK                (0x00007F3E4E827A33 [libj9prt29.so+0x27a33])
4XENATIVESTACK                (0x00007F3E4E85CCB4 [libj9prt29.so+0x5ccb4])
4XENATIVESTACK                (0x00007F3E4E858FC3 [libj9prt29.so+0x58fc3])
4XENATIVESTACK                (0x00007F3E5101A520 [libc.so.6+0x42520])
4XENATIVESTACK                (0x00007F3E51069195 [libc.so.6+0x91195])
4XENATIVESTACK               pthread_cond_wait+0x211 (0x00007F3E5106BAC1 [libc.so.6+0x93ac1])
4XENATIVESTACK               omrthread_monitor_wait+0x287 (0x00007F3E4F008937 [libj9thr29.so+0x8937])
4XENATIVESTACK                (0x00007F3E4C737C28 [libj9gc29.so+0x137c28])
4XENATIVESTACK                (0x00007F3E4C717C51 [libj9gc29.so+0x117c51])
4XENATIVESTACK                (0x00007F3E4C711EAA [libj9gc29.so+0x111eaa])
4XENATIVESTACK                (0x00007F3E4C712E11 [libj9gc29.so+0x112e11])
4XENATIVESTACK                (0x00007F3E4C803AF5 [libj9gc29.so+0x203af5])
4XENATIVESTACK                (0x00007F3E4C7336D7 [libj9gc29.so+0x1336d7])
4XENATIVESTACK                (0x00007F3E4C778266 [libj9gc29.so+0x178266])
4XENATIVESTACK                (0x00007F3E4C778C1C [libj9gc29.so+0x178c1c])
4XENATIVESTACK                (0x00007F3E4C7BF647 [libj9gc29.so+0x1bf647])
4XENATIVESTACK                (0x00007F3E4C72BC87 [libj9gc29.so+0x12bc87])
4XENATIVESTACK                (0x00007F3E4C7F6A62 [libj9gc29.so+0x1f6a62])
4XENATIVESTACK                (0x00007F3E4C7F102D [libj9gc29.so+0x1f102d])
4XENATIVESTACK                (0x00007F3E4C804C2C [libj9gc29.so+0x204c2c])
4XENATIVESTACK                (0x00007F3E4C7533AF [libj9gc29.so+0x1533af])
4XENATIVESTACK                (0x00007F3E4C7721CD [libj9gc29.so+0x1721cd])
4XENATIVESTACK                (0x00007F3E4C6487F7 [libj9gc29.so+0x487f7])
4XENATIVESTACK                (0x00007F3E4F4AE1AF [libj9vm29.so+0xae1af])
4XENATIVESTACK                (0x00007F3E4F4AE67E [libj9vm29.so+0xae67e])
4XENATIVESTACK                (0x00007F3E4F417BC5 [libj9vm29.so+0x17bc5])
4XENATIVESTACK                (0x00007F3E4F413CBC [libj9vm29.so+0x13cbc])
4XENATIVESTACK                (0x00007F3E4F5085F2 [libj9vm29.so+0x1085f2])
```

**Comment by PerfectSlayer** [comment]
cc @nikita-tkachenko-datadog
