### ISSUE TITLE
Junit4 CI Visibility breaks working test on testFinished

### ISSUE THREAD

**Issue by knokio** [DataDog/dd-trace-java#5654]
### Tested Versions:
Java: 8
Junit: 4.12
dd-java-agent.jar: 1.18.2

### Problem Statement

The Datadog CI Visibility breaks working tests. They work without the CI visibility activated.

The error I'm getting is similar to https://github.com/DataDog/dd-trace-java/issues/5268 and https://github.com/DataDog/dd-trace-java/issues/5562

```
[debug] Test client.KafkaClientTest.shouldGenerateEmptyBatchWhenNoMessages finished, took 1.338 sec

[error] Test Test mechanism failed: java.lang.IllegalStateException: Active scope does not correspond to the finished test, it is possible that end() was called multiple times or an operation that was started by the test is still in progress; active scope span is: DDSpan 
[ t_id=5593915110896785855, s_id=5528595740114404188, p_id=7391764480926675626 ] trace=kafka/kafka.consume/Consume Topic test-topic-string-861000000 *measured* 
tags={_dd.profiling.enabled=0, _dd.trace_span_attribute_schema=0, _sample_rate=1, component=java-kafka, env=ci, kafka.group=group-mapper-dGVzdC5kZXYuZXRsZWFwLmNvbTo5MDkz-1690467390476, language=jvm, 
offset=19, partition=2, process_id=25, record.queue_time_ms=2670, runtime-id=54b4a56c-817d-4763-a8e0-56e6eed71863, span.kind=consumer, thread.id=709, 
thread.name=pool-61-thread-9}, duration_ns=0, forceKeep=false; expected span is: DDSpan [ t_id=3309703662610069948, s_id=1091300163920894464, p_id=0 ] 
trace=/junit.test/client.KafkaClientTest.shouldGenerateEmptyBatchWhenNoMessages 
tags={_dd.ci.env_vars={"CIRCLE_BUILD_NUM":"328120","CIRCLE_WORKFLOW_ID":"33ba3b3d-7ec8-4ed3-b38a-ed474367091e"}, _dd.profiling.enabled=0, _dd.trace_span_attribute_schema=0, 
_sample_rate=1, ci.job.name=api-extractions-run-tests, 
ci.job.url=https://circleci.com/gh/xxx, ci.pipeline.id=33ba3b3d-7ec8-4ed3-b38a-ed474367091e, ci.pipeline.name=xxxx, 
ci.pipeline.url=https://app.circleci.com/pipelines/workflows/33ba3b3d-7ec8-4ed3-b38a-ed474367091e, 
ci.provider.name=circleci, ci.workspace_path=/root/xxxx, component=junit, env=ci, git.branch=icebreakers185706652, 
git.commit.author.email=demo@demo.com, git.commit.author.name=demo, git.commit.committer.email=demo@demo.com, 
git.commit.committer.name=demo, git.commit.sha=xxxxx, git.repository_url=git@github.com:demo/demo.git, language=jvm, 
os.architecture=amd64, os.platform=Linux, os.version=5.11.0-1028-aws, process_id=25, runtime-id=54b4a56c-817d-4763-
a8e0-56e6eed71863, runtime.name=OpenJDK Runtime Environment, runtime.vendor=Oracle Corporation, 
runtime.version=1.8.0_282, span.kind=test, test.framework=junit4, test.framework_version=4.12, 
test.name=shouldGenerateEmptyBatchWhenNoMessages, test.source.end=574, 
test.source.file=modules/connector_kafka/test/client/KafkaClientTest.java, test.source.start=549, test.status=pass, 
test.suite=client.KafkaClientTest, test.traits={"category":["util.ExternalAPITest"]}, test.type=test, thread.id=709, 
thread.name=pool-61-thread-9}, duration_ns=0, forceKeep=false, took 0.0 sec

[error]     at datadog.trace.civisibility.DDTestImpl.end(DDTestImpl.java:157)
[error]     at datadog.trace.civisibility.events.TestEventsHandlerImpl.onTestFinish(TestEventsHandlerImpl.java:310)
[error]     at datadog.trace.instrumentation.junit4.TracingListener.testFinished(TracingListener.java:119)
[error]     ...
```

**Comment by nikita-tkachenko-datadog** [comment]
Hi @knokio, thank you for reporting this!
Could you please try running your tests with dd-java-agent v1.19.0 and let me know if the issue persists?
Thanks!
