### ISSUE TITLE
IAST StringConcatFactoryCallSiteTest fails with OpenJ9 11 and higher

### ISSUE THREAD

**Issue by smola** [DataDog/dd-trace-java#5715]
Example:
```
java.lang.BootstrapMethodError: java.lang.invoke.WrongMethodTypeException: No conversion from '(Object,Object,Object,Object)Object' to '(Lookup,String,MethodType,String,Object[])Object at index (5)
	at foo.bar.TestStringConcatFactorySuite.plus(TestStringConcatFactorySuite.java:15)
	at datadog.trace.instrumentation.java.lang.invoke.StringConcatFactoryCallSiteTest.test string concat factory(StringConcatFactoryCallSiteTest.groovy:30)
Caused by: java.lang.invoke.WrongMethodTypeException: No conversion from '(Object,Object,Object,Object)Object' to '(Lookup,String,MethodType,String,Object[])Object at index (5)
	at java.lang.invoke.ConvertHandle.throwWrongMethodTypeException(ConvertHandle.java:119)
	at java.lang.invoke.ConvertHandle.checkConversion(ConvertHandle.java:59)
	at java.lang.invoke.ArgumentConversionHandle.<init>(ArgumentConversionHandle.java:31)
	at java.lang.invoke.AsTypeHandle.<init>(AsTypeHandle.java:31)
	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:475)
	at java.lang.invoke.MethodHandle.forGenericInvoke(MethodHandle.java:788)
	at java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:176)
	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
	... 2 more
```

**Comment by manuel-alvarez-alvarez** [comment]
Fixed by https://github.com/DataDog/dd-trace-java/pull/6634
