### ISSUE TITLE
tracer close does not return

### ISSUE THREAD

**Issue by florianmutter** [DataDog/dd-trace-java#6010]
With version 1.21.0 some of our java jobs in kubernetes did not stop anymore. They use 100% cpu. A thread dump shows

```
"Thread-2" #33 prio=5 os_prio=0 cpu=1487704.35ms elapsed=6002.30s tid=0x00007be964f70f10 nid=0x2f runnable  [0x00007be8f5afc000]
   java.lang.Thread.State: RUNNABLE
	at ddtrot.org.jctools.queues.MpscBlockingConsumerArrayQueue.spinWaitForElement(MpscBlockingConsumerArrayQueue.java:634)
	at ddtrot.org.jctools.queues.MpscBlockingConsumerArrayQueue.poll(MpscBlockingConsumerArrayQueue.java:614)
	at java.util.AbstractQueue.clear(java.base@17.0.2/AbstractQueue.java:147)
	at ddtrot.dd.trace.core.datastreams.DefaultDataStreamsMonitoring.close(DefaultDataStreamsMonitoring.java:272)
	at ddtrot.dd.trace.core.CoreTracer.close(CoreTracer.java:1037)
	at datadog.opentracing.DDTracer.close(DDTracer.java:522)
	at de.fadi.ngshop.lifecycle.LifecycleKt$runApplication$1$1.invoke(Lifecycle.kt:74)
	at de.fadi.ngshop.lifecycle.LifecycleKt$runApplication$1$1.invoke(Lifecycle.kt:74)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1385)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1497)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:325)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:242)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:810)
	at kotlinx.coroutines.JobImpl.complete(JobSupport.kt:1323)
	at de.fadi.ngshop.lifecycle.LifecycleKt$createShutdownHook$1.invoke(Lifecycle.kt:118)
	at de.fadi.ngshop.lifecycle.LifecycleKt$createShutdownHook$1.invoke(Lifecycle.kt:105)
	at de.fadi.ngshop.lifecycle.LifecycleKt.runApplication$lambda$1(Lifecycle.kt:85)
	at de.fadi.ngshop.lifecycle.LifecycleKt$$Lambda$242/0x0000000800ee5710.run(Unknown Source)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```

This looks to me like `close()` does not return.

**Comment by mcculls** [comment]
Hi @florianmutter - thanks for reporting this, we'll fix it before the next release
