### ISSUE TITLE
Infinite Loop in datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer

### ISSUE THREAD

**Issue by ctoestreich** [DataDog/dd-trace-java#602]
We have an issue where our rabbit messages that are destined for mysql are failing due to a data violation.  Under normal circumstances these will go through a 3x retry cycle and then bail out.  However when we have APM enabled the `TracedDelegatingConsumer` seems to "get in the way" and either eat the exception or augment the underlying default spring behavior and the message is infinitely stuck in a retry loop.

We have turned off the APM tool and this behavior goes away. 

 The exception thrown that SHOULD be causing the item to stop retrying is `o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message`.  However we the below is also added and looped infinitely when APM is enabled below.

```
2018-11-27 15:50:04.660-06:00  ERROR- [pool-1-thread-26] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1b993fb7 (amq.ctag-ztJhz2pW_o919UV5_ltoSg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773), class-id=0, method-id=0)
--
  | 2018-11-27 15:50:04.658-06:00  ERROR- [pool-1-thread-26] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1b993fb7 (amq.ctag-ztJhz2pW_o919UV5_ltoSg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.598-06:00  ERROR- [pool-1-thread-16] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@70bc6d0e (amq.ctag-Mn3tr6a-Dxt8hiUgma9EyA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.598-06:00  ERROR- [pool-1-thread-16] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@70bc6d0e (amq.ctag-Mn3tr6a-Dxt8hiUgma9EyA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64773) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.595-06:00  ERROR- [pool-1-thread-8] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@308fc027 (amq.ctag-7S5wgXceOldEEvYJ0_vPgg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.593-06:00  ERROR- [pool-1-thread-8] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@308fc027 (amq.ctag-7S5wgXceOldEEvYJ0_vPgg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.564-06:00  ERROR- [pool-1-thread-18] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5fd4299 (amq.ctag-jBQGiGL6uPi4BEdD0gu-KQ) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.563-06:00  ERROR- [pool-1-thread-18] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5fd4299 (amq.ctag-jBQGiGL6uPi4BEdD0gu-KQ) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.498-06:00  ERROR- [pool-1-thread-25] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@6dc1b602 (amq.ctag-eVXMUgZzirJkyYG2fhgwFg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.496-06:00  ERROR- [pool-1-thread-25] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@6dc1b602 (amq.ctag-eVXMUgZzirJkyYG2fhgwFg) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64772) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.496-06:00  ERROR- [pool-1-thread-7] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@3c212de3 (amq.ctag-xPibB-_KrfwniVU83-0Q-g) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64771), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.494-06:00  ERROR- [pool-1-thread-7] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@3c212de3 (amq.ctag-xPibB-_KrfwniVU83-0Q-g) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64771) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64771) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.471-06:00  ERROR- [pool-1-thread-20] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@7b014a3d (amq.ctag-nbFCrYuc-__Dc2RFRrGRhw) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.469-06:00  ERROR- [pool-1-thread-20] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@7b014a3d (amq.ctag-nbFCrYuc-__Dc2RFRrGRhw) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.391-06:00  ERROR- [pool-1-thread-12] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@42e69391 (amq.ctag-5nJKe6c17JZdKdvUc5s1pA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64769), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.390-06:00  ERROR- [pool-1-thread-12] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@42e69391 (amq.ctag-5nJKe6c17JZdKdvUc5s1pA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64769) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64769) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.390-06:00  ERROR- [pool-1-thread-14] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1ce46f8 (amq.ctag-b9RPANn6PE3f05BCZ5YYYA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.388-06:00  ERROR- [pool-1-thread-14] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1ce46f8 (amq.ctag-b9RPANn6PE3f05BCZ5YYYA) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64770) java.lang.NullPointerException: null
  | 2018-11-27 15:50:04.375-06:00  ERROR- [pool-1-thread-16] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@235112d9 (amq.ctag-464kxmffh3vP6XdYzkjRjQ) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64768), class-id=0, method-id=0)
  | 2018-11-27 15:50:04.374-06:00  ERROR- [pool-1-thread-16] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@235112d9 (amq.ctag-464kxmffh3vP6XdYzkjRjQ) method handleDelivery for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64768) threw an exception for channel AMQChannel(amqp://[scrubbed]/[scrubbed],64768) java.lang.NullPointerException: null
```

**Comment by tylerbenson** [comment]
@ctoestreich really sorry about that.  I forgot to rethrow the exception in the delegate.

Can you please try this build: https://13451-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.19.0-SNAPSHOT.jar

Note, it is based off master, so there are some additional changes since the `0.18.0` release.

Thanks again for the bug report!

**Comment by ctoestreich** [comment]
@tylerbenson I will see if I can try it out.  However, given our multiple container inheritance, deploy pipeline and test data configuration, I only WISH it were as easy as just dropping a container on k8s.  Sadly, as with all things "large corporation", this might be a few days in the making to line up all the processes and people to test this.  I will see what I can do to test this asap.

**Comment by tylerbenson** [comment]
@ctoestreich I understand.  If I don't hear back from you, I still plan to include this in the next release, so if you'd rather wait for `0.19.0` you can do that too.  Is there any reason you can think of that this wouldn't fix the bug?

**Comment by ctoestreich** [comment]
@tylerbenson I did some preliminary local testing and the issue didn't present itself with the snapshot.  However, when I use the 0.17 agent, the issue also didn't seem to be present either.  I am still working on verifying that I can actually reproduce locally with our installed APM agent 0.17.

**Comment by ctoestreich** [comment]
Here is the issue from testing the new code.

```bash
2018-11-29 14:40:35.899-06:00  ERROR- [pool-1-thread-20] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@338f00f3 (amq.ctag-RAwfZJj08DJ4p3O3lmg8Tw) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) threw an exception for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12)
java.lang.NullPointerException: null
	at datadog.trace.instrumentation.rabbitmq.amqp.TextMapExtractAdapter.<init>(TextMapExtractAdapter.java:15)
	at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:73)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Infinite loop
```

2018-11-29 14:40:40.891-06:00  ERROR- [pool-1-thread-7] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1ab71695 (amq.ctag-yVy81STzSodbtZruK1HxjQ) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12), class-id=0, method-id=0)
--
  | 2018-11-29 14:40:40.810-06:00  ERROR- [pool-1-thread-7] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@1ab71695 (amq.ctag-yVy81STzSodbtZruK1HxjQ) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) threw an exception for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) java.lang.NullPointerException: null 	at datadog.trace.instrumentation.rabbitmq.amqp.TextMapExtractAdapter.<init>(TextMapExtractAdapter.java:15) 	at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:73) 	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)Collapse
  | 2018-11-29 14:40:40.693-06:00  ERROR- [pool-1-thread-16] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@664ee90b (amq.ctag-i7f2BFqpAiF-C_m8Sh3-Eg) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12), class-id=0, method-id=0)
  | 2018-11-29 14:40:40.691-06:00  ERROR- [pool-1-thread-16] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@664ee90b (amq.ctag-i7f2BFqpAiF-C_m8Sh3-Eg) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) threw an exception for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) java.lang.NullPointerException: null 	at datadog.trace.instrumentation.rabbitmq.amqp.TextMapExtractAdapter.<init>(TextMapExtractAdapter.java:15) 	at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:73) 	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)Collapse
  | 2018-11-29 14:40:40.500-06:00  ERROR- [pool-1-thread-15] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5b690630 (amq.ctag-I09OCnYTWEs-poZXnOcZqA) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12), class-id=0, method-id=0)
  | 2018-11-29 14:40:40.499-06:00  ERROR- [pool-1-thread-15] c.r.c.impl.ForgivingExceptionHandler     : Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5b690630 (amq.ctag-I09OCnYTWEs-poZXnOcZqA) method handleDelivery for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) threw an exception for channel AMQChannel(amqp://mqprfctc@10.125.117.154:5671/cirrus_mq_perf,12) java.lang.NullPointerException: null 	at datadog.trace.instrumentation.rabbitmq.amqp.TextMapExtractAdapter.<init>(TextMapExtractAdapter.java:15) 	at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:73) 	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)


```

**Comment by ctoestreich** [comment]
@tylerbenson our header value is null so the .toString() NPE

https://github.com/DataDog/dd-trace-java/blob/66b625c6a2191e616dd64cc8250271bcaaa44a58/dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/TextMapExtractAdapter.java#L15

**Comment by realark** [comment]
Fixed in 0.19.0

**Comment by ctoestreich** [comment]
@realark I would prefer a new snapshot to test before we close issue. Unless you have an app and deployment you tested against?

**Comment by ctoestreich** [comment]
@realark I saw and understand there were into tests put in place, however I think closure is a bit premature given that there were two issues uncovered here and we still haven’t proven that our completely reproducible infinite looping scenario at runtime is resolved. We still need a snapshot jar and we will fire our tests off again to make sure the issue is resolved with the latest changes. 

We can have the tests turned around Monday.

**Comment by realark** [comment]
@ctoestreich Thanks for clarifying. Didn't realize this was more complicated than the exception being eaten by the instrumentation. I'm going to reopen this until you can confirm the fix.

It's best to test against out latest release (which as all the rabbit fixes). https://github.com/DataDog/dd-trace-java/releases/tag/v0.19.0

**Comment by ctoestreich** [comment]
Thanks. I am not trying to be difficult.  I merely will not go through our lengthy containerization and deploy process until we can verify the issue is fixed. It takes several builds and affects 100s of apps to actually bump apm and deploy your release versions into our release pipe.  This particular issue we can reproduce with a one-off container that I put in the APM agent and manually deploy to an environment. We don’t want to test issue resolution with release versions of the agent per say and I want to save you the effort of having to cut another release.
