### ISSUE TITLE
starting datadog java agent with wildfly (12) : java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jaun-rg** [DataDog/dd-trace-java#618]
current version of **datadog java agent** return a  `java.lang.IllegalArgumentException` when start with **wildfly** (12); in previous versions (`~= 0.18.0`) this problem does not present

trace:

>
> java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.AsyncHandler" for handler "{{my handler}}"
> 	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:116)
> 	at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:335)
> 	at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:288)
> 	at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:297)
> 	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
> 	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
> 	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:514)
> 	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:476)
> 	at java.util.logging.LogManager$3.run(LogManager.java:399)
> 	at java.util.logging.LogManager$3.run(LogManager.java:396)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
> 	at java.util.logging.LogManager.access$800(LogManager.java:145)
> 	at java.util.logging.LogManager$2.run(LogManager.java:345)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
> 	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
> 	at org.jboss.modules.Main.main(Main.java:513)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:114)
> 	... 17 more
> Caused by: java.lang.NoClassDefFoundError: Failed to link org/jboss/logmanager/handlers/AsyncHandler$AsyncTask (Module "org.jboss.logmanager" version 2.0.9.Final from local module loader @183e8023 (finder: local module finder @45efc20d (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/base))): datadog/trace/agent/tooling/context/FieldBackedProvider$ContextAccessor$java$lang$Runnable$datadog$trace$bootstrap$instrumentation$java$concurrent$State
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:456)
> 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:275)
> 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
> 	at org.jboss.modules.Module.loadModuleClass(Module.java:717)
> 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
> 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
> 	at org.jboss.logmanager.handlers.AsyncHandler.<init>(AsyncHandler.java:59)
> 	at org.jboss.logmanager.handlers.AsyncHandler.<init>(AsyncHandler.java:82)
> 	... 22 more
> java.lang.NoClassDefFoundError: Failed to link org/jboss/as/server/BootstrapImpl$ShutdownHook (Module "org.jboss.as.server" version 4.0.0.Final from local module loader @183e8023 (finder: local module finder @45efc20d (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/base))): datadog/trace/agent/tooling/context/FieldBackedProvider$ContextAccessor$java$lang$Runnable$datadog$trace$bootstrap$instrumentation$java$concurrent$State
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:456)
> 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:275)
> 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
> 	at org.jboss.modules.Module.loadModuleClass(Module.java:717)
> 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
> 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
> 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
> 	at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:67)
> 	at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:275)
> 	at org.jboss.as.server.Main.main(Main.java:105)
> 	at org.jboss.modules.Module.runMainMethod(Module.java:348)
> 	at org.jboss.modules.Module.run(Module.java:328)
> 	at org.jboss.modules.Main.main(Main.java:557)
>

**Comment by mar-kolya** [comment]
@jaun-rg Thanks for the bug report.

This seems to be a regression in the last release and we are working on addressing that.
I'll post an update here once we have a fix.

**Comment by stormmore** [comment]
I am also facing this issue. Reverting to 0.18.0 for now!

**Comment by stormmore** [comment]
OK I am rolling our `dev` instance of the service we saw this on and that SNAPSHOT gets passed the problem. I do not know yet if there are any follow up issues though.

**Comment by mbrouer** [comment]
Looks like the bug was reintroduced in version 0.22.

**Comment by tylerbenson** [comment]
@mbrouer do you mean 0.32?  Can I suggest you contact support to provide details? support@datadoghq.com

**Comment by mbrouer** [comment]
The fix only works in version 0.20 and 0.21.. Looks like the bug was reintroduced in version 0.22.
Version 0.32 also has the bug.

Curently I'm stuck on version 0.21

**Comment by tylerbenson** [comment]
@mbrouer please contact support. We have a [test](https://github.com/DataDog/dd-trace-java/blob/master/dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/WildflySmokeTest.groovy) that does some validation of Wildfly, so more detail for how we can reproduce would be helpful to include in the support email.
