### ISSUE TITLE
[bug] java.lang.NumberFormatException on S3 listObjects

### ISSUE THREAD

**Issue by jmayday** [DataDog/dd-trace-java#6565]
In version 1.28.0-RC3 AWS SDK instrumentation has been added:

- Log object key name to spans for AWS s3 (#6311 - @hokitam) 

This is causing issues inside application having java tracer enabled:

```
java.lang.NumberFormatException: String value 65b3c2200000000068efdfb975b540ce exceeds range of unsigned long.
	at datadog.trace.api.internal.util.LongStringUtils.numberFormatOutOfLongRange(LongStringUtils.java:130)
	at datadog.trace.api.internal.util.LongStringUtils.parseUnsignedLong(LongStringUtils.java:91)
	at datadog.trace.api.DDTraceId.from(DDTraceId.java:38)
	at datadog.trace.agent.core.CoreTracer.blackholeSpan(CoreTracer.java:894)
	at datadog.trace.bootstrap.instrumentation.api.AgentTracer.blackholeSpan(AgentTracer.java:154)
	at datadog.trace.instrumentation.aws.v0.TracingRequestHandler.beforeRequest(TracingRequestHandler.java:81)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:853)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:949)
	at <xxx>
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.run(ContextScheduler.java:184)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.lambda$execute$1(ContextScheduler.java:169)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by amarziali** [comment]
Hello, thanks for having reported this issue. This is rather linked to 128bit traceId **logging** and aws sdk instrumentation.
It's fixed by #6570
