### ISSUE TITLE
java.lang.UnsupportedOperationException from SnsInterceptor when trying to publish

### ISSUE THREAD

**Issue by v3rm0n** [DataDog/dd-trace-java#7147]
Looks like the interceptor is trying to modify an immutable collection
```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(Unknown Source)
	at com.amazonaws.internal.SdkInternalMap.put(SdkInternalMap.java:82)
	at datadog.trace.instrumentation.aws.v1.sns.SnsInterceptor.beforeMarshalling(SnsInterceptor.java:49)
	at com.amazonaws.AmazonWebServiceClient.beforeMarshalling(AmazonWebServiceClient.java:631)
	at com.amazonaws.services.sns.AmazonSNSClient.executePublish(AmazonSNSClient.java:2654)
	at com.amazonaws.services.sns.AmazonSNSClient.publish(AmazonSNSClient.java:2639)
```

**Comment by mcculls** [comment]
Hi @v3rm0n - this looks related to the new SNS instrumentation added in https://github.com/DataDog/dd-trace-java/pull/6908

As a workaround you can either use v1.34.0 or turn this integration off with this JVM option:
```
-Ddd.integration.sds.enabled=false
```
or this environment variable:
```
DD_INTEGRATION_SNS_ENABLED=false
```
