### ISSUE TITLE
java.lang.IllegalStateException: Shutdown in progress in dd-ci-git-data-uploader

### ISSUE THREAD

**Issue by jvmakine** [DataDog/dd-trace-java#7202]
I have enabled test visibility in my Gradle build with these jvm property settings for every `Test` task
```
t.systemProperties(
  mapOf(
    "dd.civisibility.enabled" to true,
    "dd.profiling.enabled" to false,
    "dd.trace.enabled" to true,
    "dd.jmxfetch.enabled" to false,
    "dd.civisibility.code.coverage.enabled" to false,
    "dd.integration.opentracing.enabled" to false,
    "dd.instrumentation.telemetry.enabled" to false,
  )
)
```
It works great, but in some tests I get this error in the logs:
```
[dd.trace 2024-06-17 04:07:03:425 +0000] [dd-ci-git-data-uploader] ERROR datadog.trace.civisibility.git.tree.GitDataUploaderImpl$$Lambda$360/0x00007ff37431cf40 - Uncaught exception java.lang.IllegalStateException: Shutdown in progress in dd-ci-git-data-uploader
--
  | java.lang.IllegalStateException: Shutdown in progress
  | at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
  | at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:245)
  | at datadog.trace.civisibility.git.tree.GitDataUploaderImpl.uploadGitData(GitDataUploaderImpl.java:170)
  | at java.base/java.lang.Thread.run(Thread.java:833)
```

It does not break the test, but is a bit annoying as it pollutes the test logs.
I am using `dd-java-agent.jar` version `1.34.0`

This is what is logged at the startup for `DATADOG TRACER CONFIGURATION`
```
[dd.trace 2024-06-17 04:07:03:059 +0000] [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"1.34.0~6666f39b87","os_name":"Linux","os_version":"6.2.0-1017-aws","architecture":"amd64","lang":"jvm","lang_version":"17.0.8.1","jvm_vendor":"Eclipse Adoptium","jvm_version":"17.0.8.1+1","java_class_version":"61.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"authz-pipeline","agent_url":"http://dd-agent:8126","agent_error":false,"debug":false,"trace_propagation_style_extract":["datadog","tracecontext"],"trace_propagation_style_inject":["datadog","tracecontext"],"analytics_enabled":false,"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":true,"remote_config_enabled":false,"debugger_enabled":false,"debugger_exception_enabled":false,"appsec_enabled":"FULLY_DISABLED","telemetry_enabled":false,"telemetry_dependency_collection_enabled":true,"telemetry_log_collection_enabled":false,"dd_version":"","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"5720e425-70b0-47da-82a7-177986582998","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false},"cws_enabled":false,"cws_tls_refresh":5000,"datadog_profiler_enabled":false,"datadog_profiler_safe":true,"datadog_profiler_enabled_overridden":false,"data_streams_enabled":false}
--
  | [dd.trace 2024-06-17 04:07:03:127 +0000] [main] INFO datadog.trace.civisibility.config.ModuleExecutionSettingsFactoryImpl - CI Visibility settings (/builds/default-i-0ddfa7111bfc5ccf3-6/cash/authz, JvmInfo{name='OpenJDK Runtime Environment', version='17.0.8.1', vendor='Eclipse Adoptium'}):
  | Per-test code coverage - false,
  | Intelligent Test Runner - false,
  | Early flakiness detection - false,
  | Flaky test retries - false
```

Is there something I could try to do to get rid of these errors in my logs?

**Comment by nikita-tkachenko-datadog** [comment]
Hi @jvmakine, thank you for reporting this!

The error that you see is not an indicator of any problem. It is a rather useless log, in fact, all it tells is that the tracer has finished Git data upload while the JVM was initiating shutdown which, depending on the timing, can happen and is normal.
I am going to suppress this log in the next tracer release.

In the meantime, I just wanted to give you a heads up that the preferred way of injecting the tracer into a Gradle build is by instrumenting the Gradle daemon itself, rather than the individual test tasks, as described [here](https://docs.datadoghq.com/tests/setup/java/?tab=gradle#running-your-tests).
The advantage that you get in this case is that longer-running operations (like uploading Git data) happen once inside the daemon process, rather than in every JVM that is forked to run tests.
So in your case replacing task instrumentation with daemon instrumentation may help you get rid of the annoying logs.
