### ISSUE TITLE
Cannot invoke "datadog.trace.civisibility.config.JvmInfo.getName()" because "jvmInfo" is null

### ISSUE THREAD

**Issue by Kalsi-Simran** [DataDog/dd-trace-java#7326]
Hi we have been trying to integrate datadog tracing for our tests. For some of our projects we see this error being printed in the console output and it's kinda weird that it happens.
Our tests run fine and we are able to trace results to datadog ..it's just this error is kinda off putting and we were hoping if there are any suggestions we can try to make it go away.
Thanks

Console output 

`[dd-ci-project-configurator] WARN datadog.trace.instrumentation.maven3.MavenLifecycleParticipant - Could not determine forked JVM path for plugin org.apache.maven.plugins:maven-surefire-plugin execution default-test in project test-regression

[2024-07-15T13:37:54.719Z] [dd.trace 2024-07-15 08:37:54:540 -0500] [main] ERROR datadog.trace.instrumentation.maven3.MavenLifecycleParticipant - Error while configuring test executions

[2024-07-15T13:37:54.719Z] java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "datadog.trace.civisibility.config.JvmInfo.getName()" because "jvmInfo" is null

[2024-07-15T13:37:54.719Z] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)

[2024-07-15T13:37:54.719Z] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)

[2024-07-15T13:37:54.719Z] 	at datadog.trace.instrumentation.maven3.MavenLifecycleParticipant.configureTestExecutions(MavenLifecycleParticipant.java:283)

[2024-07-15T13:37:54.719Z] 	at datadog.trace.instrumentation.maven3.MavenLifecycleParticipant.afterProjectsRead(MavenLifecycleParticipant.java:119)

[2024-07-15T13:37:54.719Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:223)

[2024-07-15T13:37:54.719Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)

[2024-07-15T13:37:54.719Z] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)

[2024-07-15T13:37:54.719Z] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)

[2024-07-15T13:37:54.719Z] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)

[2024-07-15T13:37:54.720Z] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)

[2024-07-15T13:37:54.720Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2024-07-15T13:37:54.720Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[2024-07-15T13:37:54.720Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2024-07-15T13:37:54.720Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[2024-07-15T13:37:54.720Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)

[2024-07-15T13:37:54.720Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)

[2024-07-15T13:37:54.720Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)

[2024-07-15T13:37:54.720Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)

[2024-07-15T13:37:54.720Z] Caused by: java.lang.NullPointerException: Cannot invoke "datadog.trace.civisibility.config.JvmInfo.getName()" because "jvmInfo" is null

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.config.ModuleExecutionSettingsFactoryImpl.buildTracerEnvironment(ModuleExecutionSettingsFactoryImpl.java:160)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.config.ModuleExecutionSettingsFactoryImpl.create(ModuleExecutionSettingsFactoryImpl.java:60)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.config.CachingModuleExecutionSettingsFactory.lambda$create$0(CachingModuleExecutionSettingsFactory.java:25)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.api.cache.FixedSizeCache.produceAndStoreValue(FixedSizeCache.java:121)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.api.cache.FixedSizeCache.computeIfAbsent(FixedSizeCache.java:85)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.config.CachingModuleExecutionSettingsFactory.create(CachingModuleExecutionSettingsFactory.java:24)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.domain.buildsystem.BuildSystemSessionImpl.getModuleExecutionSettings(BuildSystemSessionImpl.java:283)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.civisibility.events.BuildEventsHandlerImpl.getModuleExecutionSettings(BuildEventsHandlerImpl.java:149)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.instrumentation.maven3.MavenLifecycleParticipant.configureTestExecutions(MavenLifecycleParticipant.java:297)

[2024-07-15T13:37:54.720Z] 	at datadog.trace.instrumentation.maven3.MavenLifecycleParticipant.lambda$configureTestExecutions$3(MavenLifecycleParticipant.java:277)

[2024-07-15T13:37:54.720Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2024-07-15T13:37:54.720Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[2024-07-15T13:37:54.720Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2024-07-15T13:37:54.720Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[2024-07-15T13:37:54.720Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[2024-07-15T13:37:54.720Z] 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by nikita-tkachenko-datadog** [comment]
Hi @Kalsi-Simran, thank you for reporting this!
May I ask you to provide the full logs of your build? Ideally, executed with `DD_TRACE_DEBUG=true` env var for additional logging.
If you don't want to share the logs here, you can open a support ticket with Datadog to do it.

**Comment by Kalsi-Simran** [comment]
@nikita-tkachenko-datadog thanks for responding 
yeah I will create a support ticket with datadog
