### ISSUE TITLE
I have ReportGeneration Service which has access to java swing and fonts specific classes, after adding Datadog Agent through jvm, facing below issue

### ISSUE THREAD

**Issue by AvinashM7** [DataDog/dd-trace-java#738]
Servlet.service() for servlet [com.intellectseec.platform.reportgenerator.application.JerseyConfig] in context with path [/platform-reportgenerator-services] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.IllegalAccessError: superinterface check failed: class javax.swing.RepaintManager$ProcessingRunnable (in module java.desktop) cannot access class datadog.trace.bootstrap.instrumentation.context.FieldBackedProvider$ContextAccessor$java$lang$Runnable$datadog$trace$bootstrap$instrumentation$java$concurrent$State (in unnamed module @0x33308786) because module java.desktop does not read unnamed module @0x33308786] with root cause
java.lang.IllegalAccessError: superinterface check failed: class javax.swing.RepaintManager$ProcessingRunnable (in module java.desktop) cannot access class datadog.trace.bootstrap.instrumentation.context.FieldBackedProvider$ContextAccessor$java$lang$Runnable$datadog$trace$bootstrap$instrumentation$java$concurrent$State (in unnamed module @0x33308786) because module java.desktop does not read unnamed module @0x33308786
        at java.desktop/javax.swing.RepaintManager.<init>(RepaintManager.java:336)
        at java.desktop/javax.swing.RepaintManager.currentManager(RepaintManager.java:278)
        at java.desktop/javax.swing.JComponent.repaint(JComponent.java:4835)
        at java.desktop/java.awt.Component.repaint(Component.java:3394)
        at java.desktop/javax.swing.text.JTextComponent.setEditable(JTextComponent.java:1818)
        at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:323)
        at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:198)
        at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:290)
        at net.sf.jasperreports.engine.util.JEditorPaneHtmlMarkupProcessor.convert(JEditorPaneHtmlMarkupProcessor.java:82)
        at net.sf.jasperreports.engine.fill.JRFillTextElement.processMarkupText(JRFillTextElement.java:1012)
        at net.sf.jasperreports.engine.fill.JRFillTextField.evaluateText(JRFillTextField.java:571)
        at net.sf.jasperreports.engine.fill.JRFillTextField.evaluate(JRFillTextField.java:512)
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:548)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2583)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:813)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:264)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:110)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:615)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:432)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:162)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
        at com.intellectseec.platform.reportgenerator.jasper.integration.JasperReportGenerator.getReport(JasperReportGenerator.java:379)
        at com.intellectseec.platform.reportgenerator.jasper.integration.JasperReportGenerator.getFilledReport(JasperReportGenerator.java:327)
        at com.intellectseec.platform.reportgenerator.jasper.integration.JasperReportGenerator.sendGeneratedPdfReportToStream(JasperReportGenerator.java:89)
        at com.intellectseec.platform.reportgenerator.component.ReportGeneratorComponent.getGeneratedReportFromStream(ReportGeneratorComponent.java:58)
        at com.intellectseec.platform.reportgenerator.restapi.ReportGeneratorRS.generateReport(ReportGeneratorRS.java:163)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mar-kolya** [comment]
Hi @AvinashM7, thank you for your report!

Could you please provide information about JVM you are using.
Ideally small sample app that demonstrates the problem would be very helpful.

**Comment by AvinashM7** [comment]
Hi @mar-kolya , thanks for the reply!

We have dd-java-agent through Java arguments as shown below:
wget -O /platform/dd-java-agent.jar 'https://search.maven.org/classic/remote_content?g=com.datadoghq&a=dd-java-agent&v=LATEST'

java -classpath . -javaagent:/platform/dd-java-agent.jar -jar /{serviceName}.jar

Below is the code snippet where the exception is occurring:

JasperFillManager.fillReport(jasperReport,params, new JREmptyDataSource());

To give some brief explanation:
We are using Jasper Framework to generate a report, where that framework has connections with Fonts which are the platform(OS specific) dependent.
Recently I got to integrate with DataDog, in that process after integrating with DataDog using above jvm arguments provided by dataDog java agent the above-mentioned issue is occurring.

After analyzing the issue, found like there is a dynamic class package being used by datadog agent related libraries, but our runtime(Jdk11) is unable to access it.

**Comment by mar-kolya** [comment]
Hi @AvinashM7 thanks for more details on the issue.

We would have to look into this in more detail. In the meanwhile you might be able to work around this problem by adding `--add-exports` similarly to what outlined here: https://stackoverflow.com/questions/51555030/swing-issue-on-java-10

**Comment by AvinashM7** [comment]
Hi @mar-kolya 
I have tried the above option earlier with no luck.

But actually, the problem is one of the JDK class unable to find the data dog specific class which has a dynamic class package(means not available in the dd-java-agent jar)

**Comment by provcristianmaluenda** [comment]
Hi,
I am facing the same issue. Any update?

**Comment by tylerbenson** [comment]
@provcristianmaluenda would you mind raising the issue through support?  I think that will help us get further details.

**Comment by randomanderson** [comment]
This was fixed in #960 .
