### ISSUE TITLE
"Could not create service of type CiVisibilityGradleListener." when running plugin tests with ProjectBuilder.build

### ISSUE THREAD

**Issue by staktrace** [DataDog/dd-trace-java#7596]
Same datadog setup as in https://github.com/DataDog/dd-trace-java/issues/7521, but using dd-java-agent version 1.39.0. We have a gradle module that creates a gradle plugin. The test for the plugin looks like this:

```
package mypackage

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.gradle.api.GradleException
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

internal class PluginTest {
  private val project = ProjectBuilder.builder().build()

  @BeforeEach
  fun setUp() {
    project.pluginManager.run {
      apply(OurCustomPlugin::class.java)
    }
  }

  .. // @Test functions here
```

when this test is run with the datadog agent, we get an exception stack like this:

```
...

Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type CiVisibilityGradleListener.
...
Caused by: java.lang.UnsupportedOperationException: (No message provided)
at org.gradle.testfixtures.internal.ProjectBuilderImpl$TestRootBuild.getStartParameter(ProjectBuilderImpl.java:303)	
at datadog.trace.instrumentation.gradle.CiVisibilityGradleListener.getStartParameter(CiVisibilityGradleListener.java:115)	
at datadog.trace.instrumentation.gradle.CiVisibilityGradleListener.<init>(CiVisibilityGradleListener.java:105)	
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)	
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)	
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)	
at java.lang.reflect.Constructor.newInstance(Constructor.java:480)	
at org.gradle.internal.service.DefaultServiceRegistry$ConstructorService.invokeMethod(DefaultServiceRegistry.java:1158)	
at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.createServiceInstance(DefaultServiceRegistry.java:959)
```

I guess that the DD agent code is calling `getStartParameter()` on the project object but the project object is coming from the gradle testFixtures and doesn't have a start paramater? I'm not really sure.

If this information is insufficient to reproduce the problem I can try to make a sanitized standalone reproducer - please let me know!

**Comment by staktrace** [comment]
Setting that property does get the tests passing, yes. Is this something that's safe to apply on all test tasks in our shared build-logic code? Or should it generally be restricted to gradle plugin modules?

**Comment by nikita-tkachenko-datadog** [comment]
This is safe to apply everywhere. All it does is disable Gradle/Maven instrumentation, which you don't need given that you're already tracing the JVMs that execute tests.

**Comment by staktrace** [comment]
Great, thank you! In that case feel free to close out this issue. 🙇
