### ISSUE TITLE
Warning log: Failed creating custom crash upload script. Crash tracking will not work properly.

### ISSUE THREAD

**Issue by florianmutter** [DataDog/dd-trace-java#7634]
We get the following warning for some pods:

```
NOTE: Picked up JDK_JAVA_OPTIONS: -XX:MaxGCPauseMillis=4000 -XX:MinRAMPercentage=25 -XX:MaxRAMPercentage=90 -XX:MaxMetaspaceSize=128m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.rmi.port=9012 -Djava.rmi.server.hostname=10.239.78.189 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Ddatadog.slf4j.simpleLogger.logFile=System.out -Ddatadog.slf4j.simpleLogger.dateTimeFormat="yyyy-MM-dd HH:mm:ss.SSS"  -DENV=development
Picked up JAVA_TOOL_OPTIONS:  -javaagent:/datadog-lib/dd-java-agent.jar -XX:OnError=/datadog-lib/java/continuousprofiler/tmp/dd_crash_uploader.sh -XX:ErrorFile=/datadog-lib/java/continuousprofiler/tmp/hs_err_pid_%p.log
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2024-09-18 07:00:28.640 [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"1.38.0-SNAPSHOT~75639e37b3","os_name":"Linux","os_version":"6.1.85+","architecture":"amd64","lang":"jvm","lang_version":"17.0.2","jvm_vendor":"Oracle Corporation","jvm_version":"17.0.2+8-86","java_class_version":"61.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"fulfill.paqato","agent_url":"unix:///var/run/datadog/apm.socket","agent_unix_domain_socket":"/var/run/datadog/apm.socket","agent_error":false,"debug":false,"trace_propagation_style_extract":["datadog","tracecontext"],"trace_propagation_style_inject":["datadog","tracecontext"],"analytics_enabled":false,"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":false,"remote_config_enabled":true,"debugger_enabled":false,"debugger_exception_enabled":false,"appsec_enabled":"ENABLED_INACTIVE","telemetry_enabled":true,"telemetry_dependency_collection_enabled":true,"telemetry_log_collection_enabled":false,"dd_version":"rev-5575b6f7b522599c5470da8e67376033d026903f","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"71f7ad12-ae9f-44c4-b7f0-b90ae99c14eb","logging_settings":

2024-09-18 07:00:42.905 [dd-task-scheduler] WARN com.datadog.crashtracking.ScriptInitializer - Failed creating custom crash upload script. Crash tracking will not work properly.
java.nio.file.AccessDeniedException: /datadog-lib/java/continuousprofiler/tmp/dd_crash_uploader.sh
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
    at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
    at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
    at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3008)
    at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3056)
    at com.datadog.crashtracking.ScriptInitializer.writeScript(ScriptInitializer.java:253)
    at com.datadog.crashtracking.ScriptInitializer.initializeCrashUploader(ScriptInitializer.java:187)
    at com.datadog.crashtracking.ScriptInitializer.initializeCrashUploader(ScriptInitializer.java:147)
    at com.datadog.crashtracking.ScriptInitializer.initialize(ScriptInitializer.java:93)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at datadog.trace.bootstrap.Agent.initializeErrorTracking(Agent.java:881)
    at datadog.trace.bootstrap.Agent.startJmx(Agent.java:643)
    at datadog.trace.bootstrap.Agent.access$1300(Agent.java:67)
    at datadog.trace.bootstrap.Agent$JmxStartTask.run(Agent.java:631)
    at datadog.trace.util.AgentTaskScheduler$RunnableTask.run(AgentTaskScheduler.java:41)
    at datadog.trace.util.AgentTaskScheduler$RunnableTask.run(AgentTaskScheduler.java:36)
    at datadog.trace.util.AgentTaskScheduler$PeriodicTask.run(AgentTaskScheduler.java:311)
    at datadog.trace.util.AgentTaskScheduler$Worker.run(AgentTaskScheduler.java:266)
    at java.base/java.lang.Thread.run(Thread.java:833)

2024-09-18 07:00:46.370 [dd-task-scheduler] INFO datadog.communication.monitor.DDAgentStatsDConnection - Detected /var/run/datadog/dsd.socket.  Using it to send StatsD data.
```
How can we fix this?

**Comment by liangjun-jiang** [comment]
Saw the same issue when integraging Datadog Data Jobs monitoring
