### ISSUE TITLE
Cannot invoke "datadog.trace.api.civisibility.events.TestEventsHandler$Factory.create because "datadog.trace.api.civisibility.InstrumentationBridge.TEST_EVENTS_HANDLER_FACTORY" is null

### ISSUE THREAD

**Issue by Kalsi-Simran** [DataDog/dd-trace-java#8084]
Hi we started seeing dd-tracer failing on some of our builds this morning. 

ERROR LOG- 

`[2024-12-12T17:46:36.909Z] Dec 12, 2024 11:46:36 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
[2024-12-12T17:46:36.909Z] WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
[2024-12-12T17:46:36.909Z] java.lang.NullPointerException: Cannot invoke "datadog.trace.api.civisibility.events.TestEventsHandler$Factory.create(String, datadog.trace.bootstrap.ContextStore, datadog.trace.bootstrap.ContextStore)" because "datadog.trace.api.civisibility.InstrumentationBridge.TEST_EVENTS_HANDLER_FACTORY" is null
[2024-12-12T17:46:36.909Z] 	at datadog.trace.api.civisibility.InstrumentationBridge.createTestEventsHandler(InstrumentationBridge.java:28)
[2024-12-12T17:46:36.909Z] 	at datadog.trace.instrumentation.junit5.TestEventsHandlerHolder.start(TestEventsHandlerHolder.java:40)
[2024-12-12T17:46:36.909Z] 	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:66)
[2024-12-12T17:46:36.909Z] 	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
[2024-12-12T17:46:36.909Z] 	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
[2024-12-12T17:46:36.909Z] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:129)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.getSuites(JUnitPlatformProvider.java:100)
[2024-12-12T17:46:36.909Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-12T17:46:36.909Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-12-12T17:46:36.909Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-12T17:46:36.909Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.util.ReflectionUtils.invokeGetter(ReflectionUtils.java:76)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.util.ReflectionUtils.invokeGetter(ReflectionUtils.java:70)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.getSuites(ProviderFactory.java:145)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.getSuitesIterator(ForkStarter.java:697)
[2024-12-12T17:46:36.909Z] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:322)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.c.a(SourceFile:13)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.m.a(SourceFile:29)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.n.a(SourceFile:23)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.h.a(SourceFile:26)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.l.a(SourceFile:27)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.a.c(SourceFile:107)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.a.a(SourceFile:60)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.e.a(SourceFile:27)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.k.a(SourceFile:17)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.d.a(SourceFile:35)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.b.a(SourceFile:26)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.f$1.a(SourceFile:34)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r$1.a(SourceFile:29)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r$1.a(SourceFile:26)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r$2.a(SourceFile:75)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r$2.b(SourceFile:68)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r.a(SourceFile:153)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r.a(SourceFile:68)
[2024-12-12T17:46:36.910Z] 	at org.a.c.e.r.a(SourceFile:56)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.f.a(SourceFile:30)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.e.j.a(SourceFile:65)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.a.a.i.b.a(SourceFile:52)
[2024-12-12T17:46:36.910Z] 	at jdk.proxy11/jdk.proxy11.$Proxy65.execute(Unknown Source)
[2024-12-12T17:46:36.910Z] 	at com.gradle.maven.scan.extension.internal.e.a.executeMojo(SourceFile:133)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:903)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:280)
[2024-12-12T17:46:36.910Z] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:203)
[2024-12-12T17:46:36.910Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-12T17:46:36.910Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-12-12T17:46:36.910Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-12T17:46:36.910Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-12-12T17:46:36.910Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
[2024-12-12T17:46:36.910Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
[2024-12-12T17:46:36.910Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
[2024-12-12T17:46:36.910Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)`

This is how we are using the tracer 
`            try {
                withEnv(['DD_CIVISIBILITY_ENABLED=true', 'DD_ENV=staging', "DD_SERVICE=${PROJECT_NAME}", 'MAVEN_OPTS=-javaagent:/opt/datadog/dd-java-agent.jar']) {
                    sh("mvn -B -Pretry,checkenvironment " +
                            "-Dweb.url=https://www-${env.BRANCH ?: 'stage'}.test " +
                            " clean verify")
                }
            }`

**Comment by nikita-tkachenko-datadog** [comment]
Hi @Kalsi-Simran, thank you for reporting this!
The fix for this issue was released in dd-java-agent v1.44.1.
Could you please try out the new release and let me know if it fixes the issue for you?
Thanks!

**Comment by Kalsi-Simran** [comment]
Hi @nikita-tkachenko-datadog I can confirm that the latest release of tracer works fine in our build pipeline and we no longer see those issues.
thanks for fixing this so quick
