### ISSUE TITLE
feature request: Java 12 support 

### ISSUE THREAD

**Issue by wlk** [DataDog/dd-trace-java#810]
Hi,
I'm running my application with this docker image: `adoptopenjdk/openjdk12:jdk-12.33-alpine-slim` and agent version `0.26.2` (latest)

Unfortunately on startup application generates errors and tracing doesn't work:

```
java.lang.UnsupportedOperationException: Cannot get package using reflection: Cannot define nest member class java.lang.reflect.AccessibleObject$Cache + within different package then class net.bytebuddy.mirror.AccessibleObject
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getPackage(ClassInjector.java:418)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:220)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at datadog.trace.agent.tooling.HelperInjector.transform(HelperInjector.java:111)
	at net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2614)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10126)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10963)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10901)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10470)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
...
```

As far I was able to verify this is because of changes in Java 12, I'm also running several applications with OpenJDK 11 which are fine.

Can you confirm that this is the case? Is there a workaround?
Can you give some timeline when Java 12 is going to be supported?

**Comment by tylerbenson** [comment]
@raphw can you offer any advice for how to fix this?  We are using the `ClassInjector` here: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java#L111

**Comment by tylerbenson** [comment]
@raphw perhaps we just need to upgrade? https://github.com/raphw/byte-buddy/issues/631

**Comment by raphw** [comment]
I'd expect it to work with 12 and 13.

**Comment by tylerbenson** [comment]
@raphw great, thanks!  I'll get it upgraded to the latest and go from there.

**Comment by tylerbenson** [comment]
@wlk #812 should help.  Wanna try the build from that PR to confirm? https://22504-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.27.0-SNAPSHOT.jar

**Comment by wlk** [comment]
Thanks, I have tested the snapshot above and it works good on Java 12, until 0.27.0 is released I'm going to rollback to JDK 11.

**Comment by tylerbenson** [comment]
Great! Thanks for the confirmation.

**Comment by tylerbenson** [comment]
@wlk 0.27.0 is now available: https://github.com/DataDog/dd-trace-java/releases/tag/v0.27.0
