### ISSUE TITLE
Scala 2.13 support for Akka-http

### ISSUE THREAD

**Issue by dpratt** [DataDog/dd-trace-java#896]
It looks like the Java agent doesn't detect that the Scala 2.13 version of Akka-http is a candidate for auto instrumentation. I've gone through the code, and it looks like there shouldn't be anything that would make the existing implementation not work for both 2.12 and 2.13.

I do suspect that this is something quite simple to do it probably has something to do with how byte buddy does candidate matching. I'm going to spend some time trying to figure it out and send in a PR.

**Comment by dpratt** [comment]
Upon further investigation, this appears to have something to do with the fact that scala.Serializable moved from being a concrete trait that extends java.io.Serializable (and thus a compiled class file) to a type alias to java.io.Serializable. For some reason, the instrumentation for akka-http has a helper clas in it that was compiled against what looks like scala 2.11, and somewhere down the dependency tree was a class that inherited from Serializable.

I'm not sure how to isolate this and get a single artifact that works across 2.11, 2.12 and 2.13.

```
[dd.tracing.agent - 2019-06-21 13:00:32:393 -0500] ERROR datadog.trace.agent.tooling.HelperInjector - Error preparing helpers for class akka.http.scaladsl.HttpExt. Failed to inject helper classes into instance sun.misc.Launcher$AppClassLoader@18b4aac2 of type sun.misc.Launcher$AppClassLoader
java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:609)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:236)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at datadog.trace.agent.tooling.HelperInjector.transform(HelperInjector.java:111)
	at net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2614)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10126)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:1131)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:900)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
	at akka.actor.ExtensionId.apply(Extension.scala:79)
	at akka.actor.ExtensionId.apply$(Extension.scala:78)
	at akka.http.scaladsl.Http$.apply(Http.scala:1126)
	at akka.http.scaladsl.Http$.apply(Http.scala:900)
	at com.ojolabs.grpc.proxy.rest.HttpServerActor.preStart(HttpServerActor.scala:63)
	at akka.actor.Actor.aroundPreStart(Actor.scala:550)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:550)
	at com.ojolabs.grpc.proxy.rest.HttpServerActor.aroundPreStart(HttpServerActor.scala:27)
	at akka.actor.ActorCell.create(ActorCell.scala:676)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NoClassDefFoundError: scala/Serializable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:605)
	... 47 more
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more
```

**Comment by dpratt** [comment]
After looking at this a bit more, the problems are due to Scala major version binary incompatibility.

I've whipped up https://github.com/DataDog/dd-trace-java/pull/899 as a fix - I've tested this locally, and there are no exceptions at agent initialization time and traces are successfully sent for Akka-http server spans.

**Comment by papauschek** [comment]
thanks for looking into this. had to roll back our scala 2.13 deployment because of this.

**Comment by tylerbenson** [comment]
@dpratt Thanks for the PR.  We'll include this in the next release.

**Comment by dpratt** [comment]
Closed by https://github.com/DataDog/dd-trace-java/pull/899

**Comment by dpratt** [comment]
I'm happy to report that the recently released 0.31.0 version works flawlessly with akka-http and scala 2.13.

**Comment by tylerbenson** [comment]
Thanks for the update and contribution!

**Comment by tylerbenson** [comment]
@dpratt do you have any suggestions for how to change the instrumentation to support `bindAndHandle`, not just `bindAndHandleSync` and `bindAndHandleAsync`?
