### ISSUE TITLE
"Protocol wrong type for socket" error using UDS

### ISSUE THREAD

**Issue by dmitrys-svsgco** [DataDog/dd-trace-java#977]
### "Protocol wrong type for socket" error happens using UDS.

Datadog agent is deployed to Kubernetes by 
```
helm install stable/datadog \
  --name datadog \
  --namespace kube-system \
  --set datadog.apiKey=${DATADOG_API_KEY} \
  --set datadog.appKey=${DATADOG_APP_KEY} \
  --set datadog.logsEnabled=true \
  --set datadog.logsConfigContainerCollectAll=true \
  --set datadog.apmEnabled=true \
  --set datadog.useDogStatsDSocketVolume=true \
  --set datadog.dogstatsdOriginDetection=true \
  --set daemonset.useHostPID=true \
  --set datadog.limits.cpu=1000m \
  --set datadog.limits.memory=512Mi \
  --set clusterAgent.enabled=true \
  --set clusterAgent.metricsProvider.enabled=true
```

Java application is deployed by (debug is enabled):
```
     containers:
      - env:
        - name: JAVA_OPTIONS
          value: -javaagent:/dd-java-agent.jar -Djava.net.preferIPv4Stack=true
            -Ddatadog.slf4j.simpleLogger.defaultLogLevel=debug
        - name: DD_JMXFETCH_ENABLED
          value: "true"
        - name: DD_TRACE_AGENT_UNIX_DOMAIN_SOCKET
          value: /var/run/datadog/dsd.socket
...
        - mountPath: /var/run/datadog
          name: dsdsocket
          readOnly: true
...
      volumes:
      - hostPath:
          path: /var/run/datadog/
        name: dsdsocket
```
The following error happens every time opening socket connection:
```
[dd.tracing.agent - 2019-09-04 19:55:22:800 +0000] [dd-trace-writer] DEBUG datadog.trace.agent.common.writer.DDApi - Error while sending 4 of 8 traces to the DD agent.
java.io.IOException: Protocol wrong type for socket
        at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:127)
        at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:136)
        at jnr.unixsocket.UnixSocket.connect(UnixSocket.java:91)
        at datadog.trace.agent.common.writer.unixdomainsockets.TunnelingUnixSocket.connect(TunnelingUnixSocket.java:44)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at datadog.trace.agent.common.writer.DDApi.sendSerializedTraces(DDApi.java:153)
        at datadog.trace.agent.common.writer.DDAgentWriter$TraceConsumer$1.run(DDAgentWriter.java:232)
```
What could be the reason? 
I will be glad to provide all required information if needed.
Thanks!

**Comment by william-tran** [comment]
This happens because the dogstatsd socket expects UDP and traces are TCP. Leveraging UDS needs much better documentation. 

So normally, (dogstatsd) metrics goes to UDP 8125 and traces go to TCP 8126 on the host agent. dogstatsd over UDS is well documented, what isn't documented is the equivalent feature for tracing, introduced in https://github.com/DataDog/datadog-agent/commit/669a0658579e40c448e2e84a3dff695b8406ff4a

Add this to your host agent:
```yaml
      - name: DD_APM_RECEIVER_SOCKET
        value: "/var/run/datadog/apm.socket"
```

And then for the java agent:

```yaml
          DD_TRACE_AGENT_UNIX_DOMAIN_SOCKET: /var/run/datadog/apm.socket
          DD_JMXFETCH_STATSD_HOST: /var/run/datadog/dsd.socket
          DD_JMXFETCH_STATSD_PORT: "0"
```
You don't need to set DD_AGENT_HOST with all that apparently.

**Comment by randomanderson** [comment]
As there has been no activity and a solution provided, I'm closing this as resolved.  Please reopen if more help is needed.

**Comment by philippneugebauer** [comment]
I still miss this as part of the documentation
