### ISSUE TITLE
[0.32.0] Getting Provider com.fasterxml.jackson.module.paranamer.ParanamerModule not found

### ISSUE THREAD

**Issue by dragisak** [DataDog/dd-trace-java#982]
When we upgraded from 031.2 to 032.0 we started getting this error:

```
Exception in thread "main" java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.paranamer.ParanamerModule not found
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:938)
    at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:921)
    at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:957)
    at net.logstash.logback.composite.CompositeJsonFormatter.createJsonFactory(CompositeJsonFormatter.java:129)
    at net.logstash.logback.composite.CompositeJsonFormatter.start(CompositeJsonFormatter.java:103)
    at net.logstash.logback.encoder.CompositeJsonEncoder.start(CompositeJsonEncoder.java:211)
    at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
    at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
    at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
    at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
    at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
    at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
    at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
    at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
    at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
```

We use `logback-classic` (1.2.3) with `logstash-logback-encoder` (6.1)

**Comment by randomanderson** [comment]
Are you using the tracer purely as a java agent or are you implementing custom tracing with `dd-trace-api` and/or `dd-trace-ot`?

**Comment by dragisak** [comment]
Purely as java agent. Here is our command line:
```
-javaagent:/xxx/dd-java-agent-0.31.2.jar -Ddd.trace.enabled=false -Ddd.service.name=service -Ddd.agent.host=datadog -Ddd.jmxfetch.statsd.port=8125
```
Just switching path to `dd-java-agent-0.32.0.jar` throws that error when logging gets instantiated.

**Comment by tylerbenson** [comment]
Interesting... it seems you're disabling tracing and you're using it purely for JMXFetch?

Can I suggest contacting support@datadoghq.com?  They will have an easier time digging into details.

**Comment by dragisak** [comment]
My guess is that there is some incompatibility between versions of Jackson we use and the version agent uses.

**Comment by dragisak** [comment]
I would recommend "shading" your 3rd part jars before packaging them into java agent. Otherwise, you risk conflicts with libraries your users use.

**Comment by randomanderson** [comment]
Unfortunately, we haven't reproduced the issue.  The agent runs in its own classloader so there shouldn't be contamination of the user classloader.  The good news is that #1185 removes the Jackson dependency.

**Comment by dragisak** [comment]
Thank you for looking into this. We moved on with newer version of Jackson and have not had problems since.
